// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: addr_blocks.sql

package sqlc

import (
	"context"
)

const DeleteAddrBlock = `-- name: DeleteAddrBlock :exec
DELETE FROM addr_blocks WHERE height = $1
`

func (q *Queries) DeleteAddrBlock(ctx context.Context, height int64) error {
	_, err := q.db.ExecContext(ctx, DeleteAddrBlock, height)
	return err
}

const GetAddrBlockByHash = `-- name: GetAddrBlockByHash :one
SELECT height, hash, timestamp FROM addr_blocks WHERE hash = $1
`

func (q *Queries) GetAddrBlockByHash(ctx context.Context, hash []byte) (AddrBlock, error) {
	row := q.db.QueryRowContext(ctx, GetAddrBlockByHash, hash)
	var i AddrBlock
	err := row.Scan(&i.Height, &i.Hash, &i.Timestamp)
	return i, err
}

const GetAddrBlockByHeight = `-- name: GetAddrBlockByHeight :one
SELECT height, hash, timestamp FROM addr_blocks WHERE height = $1
`

func (q *Queries) GetAddrBlockByHeight(ctx context.Context, height int64) (AddrBlock, error) {
	row := q.db.QueryRowContext(ctx, GetAddrBlockByHeight, height)
	var i AddrBlock
	err := row.Scan(&i.Height, &i.Hash, &i.Timestamp)
	return i, err
}

const GetLatestAddrBlock = `-- name: GetLatestAddrBlock :one
SELECT height, hash, timestamp FROM addr_blocks ORDER BY height DESC LIMIT 1
`

func (q *Queries) GetLatestAddrBlock(ctx context.Context) (AddrBlock, error) {
	row := q.db.QueryRowContext(ctx, GetLatestAddrBlock)
	var i AddrBlock
	err := row.Scan(&i.Height, &i.Hash, &i.Timestamp)
	return i, err
}

const InsertAddrBlock = `-- name: InsertAddrBlock :exec
INSERT INTO addr_blocks (height, hash, timestamp)
VALUES ($1, $2, $3)
`

type InsertAddrBlockParams struct {
	Height    int64
	Hash      []byte
	Timestamp int32
}

func (q *Queries) InsertAddrBlock(ctx context.Context, arg InsertAddrBlockParams) error {
	_, err := q.db.ExecContext(ctx, InsertAddrBlock, arg.Height, arg.Hash, arg.Timestamp)
	return err
}
