version: "2"
run:
  # If you change this please run `make lint` to see where else it needs to be
  # updated as well.
  go: "1.24.6"

  # timeout for analysis
  timeout: 10m

linters:
  default: all
  disable:
    # Global variables are used in many places throughout the code base.
    - gochecknoglobals

    # We want to allow short variable names.
    - varnamelen

    # We want to allow TODOs.
    - godox

    # Init functions are used by loggers throughout the codebase.
    - gochecknoinits

    # Disable whitespace linter as it has conflict rules against our
    # contribution guidelines. See https://github.com/bombsimon/wsl/issues/109.
    - wsl

    # Allow using default empty values.
    - exhaustruct

    # Allow tests to be put in the same package.
    - testpackage

    # Disable tagalign.
    - tagalign

    # TODO(yy): create a list of allowed packages to import before enabling
    # this linter.
    - depguard

  # All available settings of specific linters.
  settings:
    nlreturn:
      # Size of the block (including return statement that is still "OK")
      # so no return split required.
      block-size: 3

    funlen:
      # Checks the number of lines in a function.
      # If lower than 0, disable the check.
      lines: 100
      # Checks the number of statements in a function.
      statements: 50

    whitespace:
      multi-func: true
      multi-if: true

  # Defines a set of rules to ignore issues.
  # It does not skip the analysis, and so does not ignore "typecheck" errors.
  exclusions:
    # Mode of the generated files analysis.
    #
    # - `strict`: sources are excluded by strictly following the Go generated file convention.
    #    Source files that have lines matching only the following regular expression will be excluded: `^// Code generated .* DO NOT EDIT\.$`
    #    This line must appear before the first non-comment, non-blank text in the file.
    #    https://go.dev/s/generatedcode
    # - `lax`: sources are excluded if they contain lines like `autogenerated file`, `code generated`, `do not edit`, etc.
    # - `disable`: disable the generated files exclusion.
    #
    # Default: strict
    generated: lax

    rules:
      # Exclude gosec from running for tests so that tests with weak randomness
      # (math/rand) will pass the linter.
      - path: _test\.go
        linters:
          - gosec
          - funlen
          - revive
          # Allow duplications in tests so it's easier to follow a single unit
          # test.
          - dupl

      - path: mock*
        linters:
          - revive
          # forcetypeassert is skipped for the mock because the test would fail if
          # the returned value doesn't match the type, so there's no need to check
          # the convert.
          - forcetypeassert

      # Allow fmt.Printf() in commands.
      - path: cmd/commands/*
        linters:
          - forbidigo

      # Allow fmt.Printf() in config parsing.
      - path: config\.go
        linters:
          - forbidigo

issues:
  # Show only new issues created after git revision `REV`.
  # Default: ""
  new-from-rev: a3684825d0b7511fbc5793f0c22cbfeb6f67121f
