// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcsqlite

import (
	"database/sql"
	"time"
)

type Block struct {
	BlockHeight int64
	HeaderHash  []byte
	Timestamp   int64
}

type Wallet struct {
	ID                      int64
	Name                    string
	IsImported              bool
	ManagerVersion          int64
	IsWatchOnly             bool
	MasterPubParams         []byte
	EncryptedCryptoPubKey   []byte
	EncryptedMasterHdPubKey []byte
}

type WalletSecret struct {
	WalletID                 int64
	MasterPrivParams         []byte
	EncryptedCryptoPrivKey   []byte
	EncryptedCryptoScriptKey []byte
	EncryptedMasterHdPrivKey []byte
}

type WalletSyncState struct {
	WalletID       int64
	SyncedHeight   sql.NullInt64
	BirthdayHeight sql.NullInt64
	Birthday       sql.NullTime
	UpdatedAt      time.Time
}
