// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcpg

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createWalletStmt, err = db.PrepareContext(ctx, CreateWallet); err != nil {
		return nil, fmt.Errorf("error preparing query CreateWallet: %w", err)
	}
	if q.deleteBlockStmt, err = db.PrepareContext(ctx, DeleteBlock); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBlock: %w", err)
	}
	if q.getAddressTypeByIDStmt, err = db.PrepareContext(ctx, GetAddressTypeByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetAddressTypeByID: %w", err)
	}
	if q.getBlockByHeightStmt, err = db.PrepareContext(ctx, GetBlockByHeight); err != nil {
		return nil, fmt.Errorf("error preparing query GetBlockByHeight: %w", err)
	}
	if q.getWalletByIDStmt, err = db.PrepareContext(ctx, GetWalletByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetWalletByID: %w", err)
	}
	if q.getWalletByNameStmt, err = db.PrepareContext(ctx, GetWalletByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetWalletByName: %w", err)
	}
	if q.getWalletSecretsStmt, err = db.PrepareContext(ctx, GetWalletSecrets); err != nil {
		return nil, fmt.Errorf("error preparing query GetWalletSecrets: %w", err)
	}
	if q.insertBlockStmt, err = db.PrepareContext(ctx, InsertBlock); err != nil {
		return nil, fmt.Errorf("error preparing query InsertBlock: %w", err)
	}
	if q.insertWalletSecretsStmt, err = db.PrepareContext(ctx, InsertWalletSecrets); err != nil {
		return nil, fmt.Errorf("error preparing query InsertWalletSecrets: %w", err)
	}
	if q.insertWalletSyncStateStmt, err = db.PrepareContext(ctx, InsertWalletSyncState); err != nil {
		return nil, fmt.Errorf("error preparing query InsertWalletSyncState: %w", err)
	}
	if q.listAddressTypesStmt, err = db.PrepareContext(ctx, ListAddressTypes); err != nil {
		return nil, fmt.Errorf("error preparing query ListAddressTypes: %w", err)
	}
	if q.listWalletsStmt, err = db.PrepareContext(ctx, ListWallets); err != nil {
		return nil, fmt.Errorf("error preparing query ListWallets: %w", err)
	}
	if q.updateWalletSecretsStmt, err = db.PrepareContext(ctx, UpdateWalletSecrets); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateWalletSecrets: %w", err)
	}
	if q.updateWalletSyncStateStmt, err = db.PrepareContext(ctx, UpdateWalletSyncState); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateWalletSyncState: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createWalletStmt != nil {
		if cerr := q.createWalletStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createWalletStmt: %w", cerr)
		}
	}
	if q.deleteBlockStmt != nil {
		if cerr := q.deleteBlockStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBlockStmt: %w", cerr)
		}
	}
	if q.getAddressTypeByIDStmt != nil {
		if cerr := q.getAddressTypeByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAddressTypeByIDStmt: %w", cerr)
		}
	}
	if q.getBlockByHeightStmt != nil {
		if cerr := q.getBlockByHeightStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBlockByHeightStmt: %w", cerr)
		}
	}
	if q.getWalletByIDStmt != nil {
		if cerr := q.getWalletByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getWalletByIDStmt: %w", cerr)
		}
	}
	if q.getWalletByNameStmt != nil {
		if cerr := q.getWalletByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getWalletByNameStmt: %w", cerr)
		}
	}
	if q.getWalletSecretsStmt != nil {
		if cerr := q.getWalletSecretsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getWalletSecretsStmt: %w", cerr)
		}
	}
	if q.insertBlockStmt != nil {
		if cerr := q.insertBlockStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertBlockStmt: %w", cerr)
		}
	}
	if q.insertWalletSecretsStmt != nil {
		if cerr := q.insertWalletSecretsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertWalletSecretsStmt: %w", cerr)
		}
	}
	if q.insertWalletSyncStateStmt != nil {
		if cerr := q.insertWalletSyncStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertWalletSyncStateStmt: %w", cerr)
		}
	}
	if q.listAddressTypesStmt != nil {
		if cerr := q.listAddressTypesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAddressTypesStmt: %w", cerr)
		}
	}
	if q.listWalletsStmt != nil {
		if cerr := q.listWalletsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listWalletsStmt: %w", cerr)
		}
	}
	if q.updateWalletSecretsStmt != nil {
		if cerr := q.updateWalletSecretsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateWalletSecretsStmt: %w", cerr)
		}
	}
	if q.updateWalletSyncStateStmt != nil {
		if cerr := q.updateWalletSyncStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateWalletSyncStateStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                        DBTX
	tx                        *sql.Tx
	createWalletStmt          *sql.Stmt
	deleteBlockStmt           *sql.Stmt
	getAddressTypeByIDStmt    *sql.Stmt
	getBlockByHeightStmt      *sql.Stmt
	getWalletByIDStmt         *sql.Stmt
	getWalletByNameStmt       *sql.Stmt
	getWalletSecretsStmt      *sql.Stmt
	insertBlockStmt           *sql.Stmt
	insertWalletSecretsStmt   *sql.Stmt
	insertWalletSyncStateStmt *sql.Stmt
	listAddressTypesStmt      *sql.Stmt
	listWalletsStmt           *sql.Stmt
	updateWalletSecretsStmt   *sql.Stmt
	updateWalletSyncStateStmt *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                        tx,
		tx:                        tx,
		createWalletStmt:          q.createWalletStmt,
		deleteBlockStmt:           q.deleteBlockStmt,
		getAddressTypeByIDStmt:    q.getAddressTypeByIDStmt,
		getBlockByHeightStmt:      q.getBlockByHeightStmt,
		getWalletByIDStmt:         q.getWalletByIDStmt,
		getWalletByNameStmt:       q.getWalletByNameStmt,
		getWalletSecretsStmt:      q.getWalletSecretsStmt,
		insertBlockStmt:           q.insertBlockStmt,
		insertWalletSecretsStmt:   q.insertWalletSecretsStmt,
		insertWalletSyncStateStmt: q.insertWalletSyncStateStmt,
		listAddressTypesStmt:      q.listAddressTypesStmt,
		listWalletsStmt:           q.listWalletsStmt,
		updateWalletSecretsStmt:   q.updateWalletSecretsStmt,
		updateWalletSyncStateStmt: q.updateWalletSyncStateStmt,
	}
}
