// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcpg

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createKeyScopeStmt, err = db.PrepareContext(ctx, CreateKeyScope); err != nil {
		return nil, fmt.Errorf("error preparing query CreateKeyScope: %w", err)
	}
	if q.createWalletStmt, err = db.PrepareContext(ctx, CreateWallet); err != nil {
		return nil, fmt.Errorf("error preparing query CreateWallet: %w", err)
	}
	if q.deleteBlockStmt, err = db.PrepareContext(ctx, DeleteBlock); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBlock: %w", err)
	}
	if q.deleteBlocksFromHeightOnwardsStmt, err = db.PrepareContext(ctx, DeleteBlocksFromHeightOnwards); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBlocksFromHeightOnwards: %w", err)
	}
	if q.deleteKeyScopeStmt, err = db.PrepareContext(ctx, DeleteKeyScope); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteKeyScope: %w", err)
	}
	if q.deleteKeyScopeSecretsStmt, err = db.PrepareContext(ctx, DeleteKeyScopeSecrets); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteKeyScopeSecrets: %w", err)
	}
	if q.deleteTransactionStmt, err = db.PrepareContext(ctx, DeleteTransaction); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteTransaction: %w", err)
	}
	if q.deleteUnconfirmedTransactionStmt, err = db.PrepareContext(ctx, DeleteUnconfirmedTransaction); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUnconfirmedTransaction: %w", err)
	}
	if q.getAddressTypeByIDStmt, err = db.PrepareContext(ctx, GetAddressTypeByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetAddressTypeByID: %w", err)
	}
	if q.getAllConfirmedTransactionsByHashStmt, err = db.PrepareContext(ctx, GetAllConfirmedTransactionsByHash); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllConfirmedTransactionsByHash: %w", err)
	}
	if q.getAllUnconfirmedTransactionHashesStmt, err = db.PrepareContext(ctx, GetAllUnconfirmedTransactionHashes); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllUnconfirmedTransactionHashes: %w", err)
	}
	if q.getAllUnconfirmedTransactionsStmt, err = db.PrepareContext(ctx, GetAllUnconfirmedTransactions); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllUnconfirmedTransactions: %w", err)
	}
	if q.getBlockByHeightStmt, err = db.PrepareContext(ctx, GetBlockByHeight); err != nil {
		return nil, fmt.Errorf("error preparing query GetBlockByHeight: %w", err)
	}
	if q.getKeyScopeByIDStmt, err = db.PrepareContext(ctx, GetKeyScopeByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetKeyScopeByID: %w", err)
	}
	if q.getKeyScopeByWalletAndScopeStmt, err = db.PrepareContext(ctx, GetKeyScopeByWalletAndScope); err != nil {
		return nil, fmt.Errorf("error preparing query GetKeyScopeByWalletAndScope: %w", err)
	}
	if q.getKeyScopeSecretsStmt, err = db.PrepareContext(ctx, GetKeyScopeSecrets); err != nil {
		return nil, fmt.Errorf("error preparing query GetKeyScopeSecrets: %w", err)
	}
	if q.getLatestConfirmedTransactionByHashStmt, err = db.PrepareContext(ctx, GetLatestConfirmedTransactionByHash); err != nil {
		return nil, fmt.Errorf("error preparing query GetLatestConfirmedTransactionByHash: %w", err)
	}
	if q.getTransactionByHashStmt, err = db.PrepareContext(ctx, GetTransactionByHash); err != nil {
		return nil, fmt.Errorf("error preparing query GetTransactionByHash: %w", err)
	}
	if q.getTransactionByHashAndBlockStmt, err = db.PrepareContext(ctx, GetTransactionByHashAndBlock); err != nil {
		return nil, fmt.Errorf("error preparing query GetTransactionByHashAndBlock: %w", err)
	}
	if q.getUnconfirmedTransactionByHashStmt, err = db.PrepareContext(ctx, GetUnconfirmedTransactionByHash); err != nil {
		return nil, fmt.Errorf("error preparing query GetUnconfirmedTransactionByHash: %w", err)
	}
	if q.getWalletByIDStmt, err = db.PrepareContext(ctx, GetWalletByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetWalletByID: %w", err)
	}
	if q.getWalletByNameStmt, err = db.PrepareContext(ctx, GetWalletByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetWalletByName: %w", err)
	}
	if q.getWalletSecretsStmt, err = db.PrepareContext(ctx, GetWalletSecrets); err != nil {
		return nil, fmt.Errorf("error preparing query GetWalletSecrets: %w", err)
	}
	if q.insertBlockStmt, err = db.PrepareContext(ctx, InsertBlock); err != nil {
		return nil, fmt.Errorf("error preparing query InsertBlock: %w", err)
	}
	if q.insertKeyScopeSecretsStmt, err = db.PrepareContext(ctx, InsertKeyScopeSecrets); err != nil {
		return nil, fmt.Errorf("error preparing query InsertKeyScopeSecrets: %w", err)
	}
	if q.insertTransactionStmt, err = db.PrepareContext(ctx, InsertTransaction); err != nil {
		return nil, fmt.Errorf("error preparing query InsertTransaction: %w", err)
	}
	if q.insertWalletSecretsStmt, err = db.PrepareContext(ctx, InsertWalletSecrets); err != nil {
		return nil, fmt.Errorf("error preparing query InsertWalletSecrets: %w", err)
	}
	if q.insertWalletSyncStateStmt, err = db.PrepareContext(ctx, InsertWalletSyncState); err != nil {
		return nil, fmt.Errorf("error preparing query InsertWalletSyncState: %w", err)
	}
	if q.listAddressTypesStmt, err = db.PrepareContext(ctx, ListAddressTypes); err != nil {
		return nil, fmt.Errorf("error preparing query ListAddressTypes: %w", err)
	}
	if q.listKeyScopesByWalletStmt, err = db.PrepareContext(ctx, ListKeyScopesByWallet); err != nil {
		return nil, fmt.Errorf("error preparing query ListKeyScopesByWallet: %w", err)
	}
	if q.listTransactionsByHeightRangeStmt, err = db.PrepareContext(ctx, ListTransactionsByHeightRange); err != nil {
		return nil, fmt.Errorf("error preparing query ListTransactionsByHeightRange: %w", err)
	}
	if q.listWalletsStmt, err = db.PrepareContext(ctx, ListWallets); err != nil {
		return nil, fmt.Errorf("error preparing query ListWallets: %w", err)
	}
	if q.transactionExistsStmt, err = db.PrepareContext(ctx, TransactionExists); err != nil {
		return nil, fmt.Errorf("error preparing query TransactionExists: %w", err)
	}
	if q.unconfirmTransactionsFromHeightStmt, err = db.PrepareContext(ctx, UnconfirmTransactionsFromHeight); err != nil {
		return nil, fmt.Errorf("error preparing query UnconfirmTransactionsFromHeight: %w", err)
	}
	if q.unconfirmedTransactionExistsStmt, err = db.PrepareContext(ctx, UnconfirmedTransactionExists); err != nil {
		return nil, fmt.Errorf("error preparing query UnconfirmedTransactionExists: %w", err)
	}
	if q.updateTransactionBlockStmt, err = db.PrepareContext(ctx, UpdateTransactionBlock); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateTransactionBlock: %w", err)
	}
	if q.updateTransactionLabelStmt, err = db.PrepareContext(ctx, UpdateTransactionLabel); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateTransactionLabel: %w", err)
	}
	if q.updateWalletSecretsStmt, err = db.PrepareContext(ctx, UpdateWalletSecrets); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateWalletSecrets: %w", err)
	}
	if q.updateWalletSyncStateStmt, err = db.PrepareContext(ctx, UpdateWalletSyncState); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateWalletSyncState: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createKeyScopeStmt != nil {
		if cerr := q.createKeyScopeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createKeyScopeStmt: %w", cerr)
		}
	}
	if q.createWalletStmt != nil {
		if cerr := q.createWalletStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createWalletStmt: %w", cerr)
		}
	}
	if q.deleteBlockStmt != nil {
		if cerr := q.deleteBlockStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBlockStmt: %w", cerr)
		}
	}
	if q.deleteBlocksFromHeightOnwardsStmt != nil {
		if cerr := q.deleteBlocksFromHeightOnwardsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBlocksFromHeightOnwardsStmt: %w", cerr)
		}
	}
	if q.deleteKeyScopeStmt != nil {
		if cerr := q.deleteKeyScopeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteKeyScopeStmt: %w", cerr)
		}
	}
	if q.deleteKeyScopeSecretsStmt != nil {
		if cerr := q.deleteKeyScopeSecretsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteKeyScopeSecretsStmt: %w", cerr)
		}
	}
	if q.deleteTransactionStmt != nil {
		if cerr := q.deleteTransactionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteTransactionStmt: %w", cerr)
		}
	}
	if q.deleteUnconfirmedTransactionStmt != nil {
		if cerr := q.deleteUnconfirmedTransactionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUnconfirmedTransactionStmt: %w", cerr)
		}
	}
	if q.getAddressTypeByIDStmt != nil {
		if cerr := q.getAddressTypeByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAddressTypeByIDStmt: %w", cerr)
		}
	}
	if q.getAllConfirmedTransactionsByHashStmt != nil {
		if cerr := q.getAllConfirmedTransactionsByHashStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllConfirmedTransactionsByHashStmt: %w", cerr)
		}
	}
	if q.getAllUnconfirmedTransactionHashesStmt != nil {
		if cerr := q.getAllUnconfirmedTransactionHashesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllUnconfirmedTransactionHashesStmt: %w", cerr)
		}
	}
	if q.getAllUnconfirmedTransactionsStmt != nil {
		if cerr := q.getAllUnconfirmedTransactionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllUnconfirmedTransactionsStmt: %w", cerr)
		}
	}
	if q.getBlockByHeightStmt != nil {
		if cerr := q.getBlockByHeightStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBlockByHeightStmt: %w", cerr)
		}
	}
	if q.getKeyScopeByIDStmt != nil {
		if cerr := q.getKeyScopeByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getKeyScopeByIDStmt: %w", cerr)
		}
	}
	if q.getKeyScopeByWalletAndScopeStmt != nil {
		if cerr := q.getKeyScopeByWalletAndScopeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getKeyScopeByWalletAndScopeStmt: %w", cerr)
		}
	}
	if q.getKeyScopeSecretsStmt != nil {
		if cerr := q.getKeyScopeSecretsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getKeyScopeSecretsStmt: %w", cerr)
		}
	}
	if q.getLatestConfirmedTransactionByHashStmt != nil {
		if cerr := q.getLatestConfirmedTransactionByHashStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLatestConfirmedTransactionByHashStmt: %w", cerr)
		}
	}
	if q.getTransactionByHashStmt != nil {
		if cerr := q.getTransactionByHashStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTransactionByHashStmt: %w", cerr)
		}
	}
	if q.getTransactionByHashAndBlockStmt != nil {
		if cerr := q.getTransactionByHashAndBlockStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTransactionByHashAndBlockStmt: %w", cerr)
		}
	}
	if q.getUnconfirmedTransactionByHashStmt != nil {
		if cerr := q.getUnconfirmedTransactionByHashStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUnconfirmedTransactionByHashStmt: %w", cerr)
		}
	}
	if q.getWalletByIDStmt != nil {
		if cerr := q.getWalletByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getWalletByIDStmt: %w", cerr)
		}
	}
	if q.getWalletByNameStmt != nil {
		if cerr := q.getWalletByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getWalletByNameStmt: %w", cerr)
		}
	}
	if q.getWalletSecretsStmt != nil {
		if cerr := q.getWalletSecretsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getWalletSecretsStmt: %w", cerr)
		}
	}
	if q.insertBlockStmt != nil {
		if cerr := q.insertBlockStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertBlockStmt: %w", cerr)
		}
	}
	if q.insertKeyScopeSecretsStmt != nil {
		if cerr := q.insertKeyScopeSecretsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertKeyScopeSecretsStmt: %w", cerr)
		}
	}
	if q.insertTransactionStmt != nil {
		if cerr := q.insertTransactionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertTransactionStmt: %w", cerr)
		}
	}
	if q.insertWalletSecretsStmt != nil {
		if cerr := q.insertWalletSecretsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertWalletSecretsStmt: %w", cerr)
		}
	}
	if q.insertWalletSyncStateStmt != nil {
		if cerr := q.insertWalletSyncStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertWalletSyncStateStmt: %w", cerr)
		}
	}
	if q.listAddressTypesStmt != nil {
		if cerr := q.listAddressTypesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAddressTypesStmt: %w", cerr)
		}
	}
	if q.listKeyScopesByWalletStmt != nil {
		if cerr := q.listKeyScopesByWalletStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listKeyScopesByWalletStmt: %w", cerr)
		}
	}
	if q.listTransactionsByHeightRangeStmt != nil {
		if cerr := q.listTransactionsByHeightRangeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTransactionsByHeightRangeStmt: %w", cerr)
		}
	}
	if q.listWalletsStmt != nil {
		if cerr := q.listWalletsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listWalletsStmt: %w", cerr)
		}
	}
	if q.transactionExistsStmt != nil {
		if cerr := q.transactionExistsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing transactionExistsStmt: %w", cerr)
		}
	}
	if q.unconfirmTransactionsFromHeightStmt != nil {
		if cerr := q.unconfirmTransactionsFromHeightStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing unconfirmTransactionsFromHeightStmt: %w", cerr)
		}
	}
	if q.unconfirmedTransactionExistsStmt != nil {
		if cerr := q.unconfirmedTransactionExistsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing unconfirmedTransactionExistsStmt: %w", cerr)
		}
	}
	if q.updateTransactionBlockStmt != nil {
		if cerr := q.updateTransactionBlockStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateTransactionBlockStmt: %w", cerr)
		}
	}
	if q.updateTransactionLabelStmt != nil {
		if cerr := q.updateTransactionLabelStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateTransactionLabelStmt: %w", cerr)
		}
	}
	if q.updateWalletSecretsStmt != nil {
		if cerr := q.updateWalletSecretsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateWalletSecretsStmt: %w", cerr)
		}
	}
	if q.updateWalletSyncStateStmt != nil {
		if cerr := q.updateWalletSyncStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateWalletSyncStateStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                      DBTX
	tx                                      *sql.Tx
	createKeyScopeStmt                      *sql.Stmt
	createWalletStmt                        *sql.Stmt
	deleteBlockStmt                         *sql.Stmt
	deleteBlocksFromHeightOnwardsStmt       *sql.Stmt
	deleteKeyScopeStmt                      *sql.Stmt
	deleteKeyScopeSecretsStmt               *sql.Stmt
	deleteTransactionStmt                   *sql.Stmt
	deleteUnconfirmedTransactionStmt        *sql.Stmt
	getAddressTypeByIDStmt                  *sql.Stmt
	getAllConfirmedTransactionsByHashStmt   *sql.Stmt
	getAllUnconfirmedTransactionHashesStmt  *sql.Stmt
	getAllUnconfirmedTransactionsStmt       *sql.Stmt
	getBlockByHeightStmt                    *sql.Stmt
	getKeyScopeByIDStmt                     *sql.Stmt
	getKeyScopeByWalletAndScopeStmt         *sql.Stmt
	getKeyScopeSecretsStmt                  *sql.Stmt
	getLatestConfirmedTransactionByHashStmt *sql.Stmt
	getTransactionByHashStmt                *sql.Stmt
	getTransactionByHashAndBlockStmt        *sql.Stmt
	getUnconfirmedTransactionByHashStmt     *sql.Stmt
	getWalletByIDStmt                       *sql.Stmt
	getWalletByNameStmt                     *sql.Stmt
	getWalletSecretsStmt                    *sql.Stmt
	insertBlockStmt                         *sql.Stmt
	insertKeyScopeSecretsStmt               *sql.Stmt
	insertTransactionStmt                   *sql.Stmt
	insertWalletSecretsStmt                 *sql.Stmt
	insertWalletSyncStateStmt               *sql.Stmt
	listAddressTypesStmt                    *sql.Stmt
	listKeyScopesByWalletStmt               *sql.Stmt
	listTransactionsByHeightRangeStmt       *sql.Stmt
	listWalletsStmt                         *sql.Stmt
	transactionExistsStmt                   *sql.Stmt
	unconfirmTransactionsFromHeightStmt     *sql.Stmt
	unconfirmedTransactionExistsStmt        *sql.Stmt
	updateTransactionBlockStmt              *sql.Stmt
	updateTransactionLabelStmt              *sql.Stmt
	updateWalletSecretsStmt                 *sql.Stmt
	updateWalletSyncStateStmt               *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                      tx,
		tx:                                      tx,
		createKeyScopeStmt:                      q.createKeyScopeStmt,
		createWalletStmt:                        q.createWalletStmt,
		deleteBlockStmt:                         q.deleteBlockStmt,
		deleteBlocksFromHeightOnwardsStmt:       q.deleteBlocksFromHeightOnwardsStmt,
		deleteKeyScopeStmt:                      q.deleteKeyScopeStmt,
		deleteKeyScopeSecretsStmt:               q.deleteKeyScopeSecretsStmt,
		deleteTransactionStmt:                   q.deleteTransactionStmt,
		deleteUnconfirmedTransactionStmt:        q.deleteUnconfirmedTransactionStmt,
		getAddressTypeByIDStmt:                  q.getAddressTypeByIDStmt,
		getAllConfirmedTransactionsByHashStmt:   q.getAllConfirmedTransactionsByHashStmt,
		getAllUnconfirmedTransactionHashesStmt:  q.getAllUnconfirmedTransactionHashesStmt,
		getAllUnconfirmedTransactionsStmt:       q.getAllUnconfirmedTransactionsStmt,
		getBlockByHeightStmt:                    q.getBlockByHeightStmt,
		getKeyScopeByIDStmt:                     q.getKeyScopeByIDStmt,
		getKeyScopeByWalletAndScopeStmt:         q.getKeyScopeByWalletAndScopeStmt,
		getKeyScopeSecretsStmt:                  q.getKeyScopeSecretsStmt,
		getLatestConfirmedTransactionByHashStmt: q.getLatestConfirmedTransactionByHashStmt,
		getTransactionByHashStmt:                q.getTransactionByHashStmt,
		getTransactionByHashAndBlockStmt:        q.getTransactionByHashAndBlockStmt,
		getUnconfirmedTransactionByHashStmt:     q.getUnconfirmedTransactionByHashStmt,
		getWalletByIDStmt:                       q.getWalletByIDStmt,
		getWalletByNameStmt:                     q.getWalletByNameStmt,
		getWalletSecretsStmt:                    q.getWalletSecretsStmt,
		insertBlockStmt:                         q.insertBlockStmt,
		insertKeyScopeSecretsStmt:               q.insertKeyScopeSecretsStmt,
		insertTransactionStmt:                   q.insertTransactionStmt,
		insertWalletSecretsStmt:                 q.insertWalletSecretsStmt,
		insertWalletSyncStateStmt:               q.insertWalletSyncStateStmt,
		listAddressTypesStmt:                    q.listAddressTypesStmt,
		listKeyScopesByWalletStmt:               q.listKeyScopesByWalletStmt,
		listTransactionsByHeightRangeStmt:       q.listTransactionsByHeightRangeStmt,
		listWalletsStmt:                         q.listWalletsStmt,
		transactionExistsStmt:                   q.transactionExistsStmt,
		unconfirmTransactionsFromHeightStmt:     q.unconfirmTransactionsFromHeightStmt,
		unconfirmedTransactionExistsStmt:        q.unconfirmedTransactionExistsStmt,
		updateTransactionBlockStmt:              q.updateTransactionBlockStmt,
		updateTransactionLabelStmt:              q.updateTransactionLabelStmt,
		updateWalletSecretsStmt:                 q.updateWalletSecretsStmt,
		updateWalletSyncStateStmt:               q.updateWalletSyncStateStmt,
	}
}
