// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: address_types.sql

package sqlc

import (
	"context"
)

const ListAddressTypes = `-- name: ListAddressTypes :many
SELECT id, type_name
FROM address_types
ORDER BY id
`

func (q *Queries) ListAddressTypes(ctx context.Context) ([]AddressType, error) {
	rows, err := q.query(ctx, q.listAddressTypesStmt, ListAddressTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AddressType
	for rows.Next() {
		var i AddressType
		if err := rows.Scan(&i.ID, &i.TypeName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
