// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	AcquireOutputLease(ctx context.Context, arg AcquireOutputLeaseParams) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) error
	CreateAddress(ctx context.Context, arg CreateAddressParams) error
	CreateKeyScope(ctx context.Context, arg CreateKeyScopeParams) (int64, error)
	CreateWallet(ctx context.Context, arg CreateWalletParams) (int64, error)
	DeleteAccountPrivateKeys(ctx context.Context, walletID int64) (int64, error)
	DeleteAddressPrivateKeys(ctx context.Context, walletID int64) (int64, error)
	DeleteBlock(ctx context.Context, blockHeight int32) error
	DeleteCreditSpend(ctx context.Context, arg DeleteCreditSpendParams) (int64, error)
	DeleteCreditSpendsBySpendingTx(ctx context.Context, arg DeleteCreditSpendsBySpendingTxParams) (int64, error)
	DeleteExpiredOutputLeases(ctx context.Context, arg DeleteExpiredOutputLeasesParams) (int64, error)
	DeleteKeyScopePrivateKeys(ctx context.Context, walletID int64) (int64, error)
	DeleteManagerPrivateKeys(ctx context.Context, id int64) (int64, error)
	DeleteOutputLease(ctx context.Context, arg DeleteOutputLeaseParams) (int64, error)
	DeleteOutputLeaseAnyOwner(ctx context.Context, arg DeleteOutputLeaseAnyOwnerParams) (int64, error)
	DeleteTransactionByID(ctx context.Context, arg DeleteTransactionByIDParams) (int64, error)
	DetachMinedTransaction(ctx context.Context, arg DetachMinedTransactionParams) (int64, error)
	GetAccount(ctx context.Context, arg GetAccountParams) (Account, error)
	GetActiveCreditID(ctx context.Context, arg GetActiveCreditIDParams) (int64, error)
	GetAddress(ctx context.Context, arg GetAddressParams) (Address, error)
	GetBlockByHeight(ctx context.Context, blockHeight int32) (Block, error)
	GetBlocksInRange(ctx context.Context, arg GetBlocksInRangeParams) ([]Block, error)
	GetCredit(ctx context.Context, arg GetCreditParams) (Credit, error)
	GetKeyScope(ctx context.Context, arg GetKeyScopeParams) (KeyScope, error)
	GetManagerAccount(ctx context.Context, arg GetManagerAccountParams) (Account, error)
	GetManagerAccountByName(ctx context.Context, arg GetManagerAccountByNameParams) (Account, error)
	GetManagerAddress(ctx context.Context, arg GetManagerAddressParams) (Address, error)
	GetManagerState(ctx context.Context, id int64) (GetManagerStateRow, error)
	GetMinedPreviousPkScript(ctx context.Context, arg GetMinedPreviousPkScriptParams) ([]byte, error)
	GetMinedTransactionByIncidence(ctx context.Context, arg GetMinedTransactionByIncidenceParams) (Transaction, error)
	GetMinedTransactionDetails(ctx context.Context, arg GetMinedTransactionDetailsParams) (GetMinedTransactionDetailsRow, error)
	GetMinedTransactionID(ctx context.Context, arg GetMinedTransactionIDParams) (int64, error)
	GetOutputLease(ctx context.Context, arg GetOutputLeaseParams) (UtxoLease, error)
	GetTransactionDetailsByHash(ctx context.Context, arg GetTransactionDetailsByHashParams) (GetTransactionDetailsByHashRow, error)
	GetTransactionDetailsByID(ctx context.Context, arg GetTransactionDetailsByIDParams) (GetTransactionDetailsByIDRow, error)
	GetTransactionLabel(ctx context.Context, arg GetTransactionLabelParams) ([]byte, error)
	GetUnminedPreviousPkScript(ctx context.Context, arg GetUnminedPreviousPkScriptParams) ([]byte, error)
	GetUnminedTransactionByHash(ctx context.Context, arg GetUnminedTransactionByHashParams) (Transaction, error)
	GetUnminedTransactionDetails(ctx context.Context, arg GetUnminedTransactionDetailsParams) (GetUnminedTransactionDetailsRow, error)
	GetWalletByName(ctx context.Context, walletName string) (Wallet, error)
	GetWalletStartBlock(ctx context.Context, walletID int64) (Block, error)
	GetWalletSyncState(ctx context.Context, walletID int64) (GetWalletSyncStateRow, error)
	InsertBlock(ctx context.Context, arg InsertBlockParams) error
	InsertCredit(ctx context.Context, arg InsertCreditParams) (int64, error)
	InsertTransaction(ctx context.Context, arg InsertTransactionParams) (int64, error)
	InsertTransactionInput(ctx context.Context, arg InsertTransactionInputParams) error
	IsKnownOutput(ctx context.Context, arg IsKnownOutputParams) (bool, error)
	ListAccountAddresses(ctx context.Context, arg ListAccountAddressesParams) ([]Address, error)
	ListAccounts(ctx context.Context, scopeID int64) ([]Account, error)
	ListActiveOutputLeases(ctx context.Context, arg ListActiveOutputLeasesParams) ([]UtxoLease, error)
	ListAddressTypes(ctx context.Context) ([]AddressType, error)
	ListKeyScopes(ctx context.Context, walletID int64) ([]KeyScope, error)
	ListManagerAccountAddresses(ctx context.Context, arg ListManagerAccountAddressesParams) ([]Address, error)
	ListManagerAccounts(ctx context.Context, arg ListManagerAccountsParams) ([]Account, error)
	ListManagerActiveAddresses(ctx context.Context, arg ListManagerActiveAddressesParams) ([]Address, error)
	ListMinedTransactionsForward(ctx context.Context, arg ListMinedTransactionsForwardParams) ([]ListMinedTransactionsForwardRow, error)
	ListMinedTransactionsFromHeight(ctx context.Context, arg ListMinedTransactionsFromHeightParams) ([]ListMinedTransactionsFromHeightRow, error)
	ListMinedTransactionsReverse(ctx context.Context, arg ListMinedTransactionsReverseParams) ([]ListMinedTransactionsReverseRow, error)
	ListOutputsToWatch(ctx context.Context, walletID int64) ([]ListOutputsToWatchRow, error)
	ListTransactionCredits(ctx context.Context, arg ListTransactionCreditsParams) ([]ListTransactionCreditsRow, error)
	ListTransactionDebits(ctx context.Context, arg ListTransactionDebitsParams) ([]ListTransactionDebitsRow, error)
	ListTransactionIncidencesByHash(ctx context.Context, arg ListTransactionIncidencesByHashParams) ([]Transaction, error)
	ListUnminedSpenders(ctx context.Context, arg ListUnminedSpendersParams) ([]ListUnminedSpendersRow, error)
	ListUnminedSpendersByPrevHash(ctx context.Context, arg ListUnminedSpendersByPrevHashParams) ([]ListUnminedSpendersByPrevHashRow, error)
	ListUnminedTransactions(ctx context.Context, walletID int64) ([]Transaction, error)
	ListUnspentCredits(ctx context.Context, arg ListUnspentCreditsParams) ([]ListUnspentCreditsRow, error)
	MarkAddressUsed(ctx context.Context, arg MarkAddressUsedParams) (int64, error)
	NextBlockTransactionOrder(ctx context.Context, arg NextBlockTransactionOrderParams) (int64, error)
	PromoteUnminedTransaction(ctx context.Context, arg PromoteUnminedTransactionParams) (int64, error)
	PutBlock(ctx context.Context, arg PutBlockParams) error
	PutKeyScope(ctx context.Context, arg PutKeyScopeParams) (int64, error)
	PutManagerAccount(ctx context.Context, arg PutManagerAccountParams) (int64, error)
	PutManagerAddress(ctx context.Context, arg PutManagerAddressParams) (int64, error)
	PutManagerState(ctx context.Context, arg PutManagerStateParams) (int64, error)
	PutTransactionLabel(ctx context.Context, arg PutTransactionLabelParams) error
	PutWalletSyncState(ctx context.Context, arg PutWalletSyncStateParams) error
	RecordCreditSpend(ctx context.Context, arg RecordCreditSpendParams) (int64, error)
	RenameAccount(ctx context.Context, arg RenameAccountParams) (int64, error)
	SetActiveCreditIncidence(ctx context.Context, arg SetActiveCreditIncidenceParams) error
	SetWalletBirthday(ctx context.Context, arg SetWalletBirthdayParams) (int64, error)
	SetWalletBirthdayBlock(ctx context.Context, arg SetWalletBirthdayBlockParams) (int64, error)
	SetWalletBirthdayBlockVerified(ctx context.Context, arg SetWalletBirthdayBlockVerifiedParams) (int64, error)
	SetWalletSyncedTo(ctx context.Context, arg SetWalletSyncedToParams) (int64, error)
	UpdateAccountIndexes(ctx context.Context, arg UpdateAccountIndexesParams) (int64, error)
	UpdateKeyScopeKeys(ctx context.Context, arg UpdateKeyScopeKeysParams) (int64, error)
	UpdateLastAccountNumber(ctx context.Context, arg UpdateLastAccountNumberParams) (int64, error)
	UpdateWalletEncryption(ctx context.Context, arg UpdateWalletEncryptionParams) (int64, error)
	UpdateWalletSyncState(ctx context.Context, arg UpdateWalletSyncStateParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
