// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package sqlc

import (
	"context"
	"database/sql"
)

const DeleteTransactionByID = `-- name: DeleteTransactionByID :execrows
DELETE FROM transactions WHERE wallet_id = $1 AND id = $2
`

type DeleteTransactionByIDParams struct {
	WalletID int64
	ID       int64
}

func (q *Queries) DeleteTransactionByID(ctx context.Context, arg DeleteTransactionByIDParams) (int64, error) {
	result, err := q.exec(ctx, q.deleteTransactionByIDStmt, DeleteTransactionByID, arg.WalletID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const GetMinedTransactionByIncidence = `-- name: GetMinedTransactionByIncidence :one
SELECT t.id, t.wallet_id, t.tx_hash, t.raw_tx, t.received_unix,
       t.block_height, t.confirmed_order, t.is_coinbase
FROM transactions AS t
INNER JOIN blocks AS b ON b.block_height = t.block_height
WHERE t.wallet_id = $1
  AND t.tx_hash = $2
  AND t.block_height = $3
  AND b.header_hash = $4
`

type GetMinedTransactionByIncidenceParams struct {
	WalletID    int64
	TxHash      []byte
	BlockHeight sql.NullInt32
	BlockHash   []byte
}

func (q *Queries) GetMinedTransactionByIncidence(ctx context.Context, arg GetMinedTransactionByIncidenceParams) (Transaction, error) {
	row := q.queryRow(ctx, q.getMinedTransactionByIncidenceStmt, GetMinedTransactionByIncidence,
		arg.WalletID,
		arg.TxHash,
		arg.BlockHeight,
		arg.BlockHash,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.TxHash,
		&i.RawTx,
		&i.ReceivedUnix,
		&i.BlockHeight,
		&i.ConfirmedOrder,
		&i.IsCoinbase,
	)
	return i, err
}

const GetTransactionLabel = `-- name: GetTransactionLabel :one
SELECT label FROM transaction_labels WHERE wallet_id = $1 AND tx_hash = $2
`

type GetTransactionLabelParams struct {
	WalletID int64
	TxHash   []byte
}

func (q *Queries) GetTransactionLabel(ctx context.Context, arg GetTransactionLabelParams) ([]byte, error) {
	row := q.queryRow(ctx, q.getTransactionLabelStmt, GetTransactionLabel, arg.WalletID, arg.TxHash)
	var label []byte
	err := row.Scan(&label)
	return label, err
}

const GetUnminedTransactionByHash = `-- name: GetUnminedTransactionByHash :one
SELECT id, wallet_id, tx_hash, raw_tx, received_unix, block_height,
       confirmed_order, is_coinbase
FROM transactions
WHERE wallet_id = $1 AND tx_hash = $2 AND block_height IS NULL
`

type GetUnminedTransactionByHashParams struct {
	WalletID int64
	TxHash   []byte
}

func (q *Queries) GetUnminedTransactionByHash(ctx context.Context, arg GetUnminedTransactionByHashParams) (Transaction, error) {
	row := q.queryRow(ctx, q.getUnminedTransactionByHashStmt, GetUnminedTransactionByHash, arg.WalletID, arg.TxHash)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.TxHash,
		&i.RawTx,
		&i.ReceivedUnix,
		&i.BlockHeight,
		&i.ConfirmedOrder,
		&i.IsCoinbase,
	)
	return i, err
}

const InsertTransaction = `-- name: InsertTransaction :one
INSERT INTO transactions (
    wallet_id, tx_hash, raw_tx, received_unix, block_height,
    confirmed_order, is_coinbase
) VALUES (
    $1, $2, $3,
    $4, $5::INTEGER,
    $6::BIGINT, $7
)
RETURNING id
`

type InsertTransactionParams struct {
	WalletID       int64
	TxHash         []byte
	RawTx          []byte
	ReceivedUnix   int64
	BlockHeight    sql.NullInt32
	ConfirmedOrder sql.NullInt64
	IsCoinbase     bool
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (int64, error) {
	row := q.queryRow(ctx, q.insertTransactionStmt, InsertTransaction,
		arg.WalletID,
		arg.TxHash,
		arg.RawTx,
		arg.ReceivedUnix,
		arg.BlockHeight,
		arg.ConfirmedOrder,
		arg.IsCoinbase,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const InsertTransactionInput = `-- name: InsertTransactionInput :exec
INSERT INTO transaction_inputs (
    spending_tx_id, input_index, prev_tx_hash, prev_output_index
) VALUES ($1, $2, $3, $4)
`

type InsertTransactionInputParams struct {
	SpendingTxID    int64
	InputIndex      int64
	PrevTxHash      []byte
	PrevOutputIndex int64
}

func (q *Queries) InsertTransactionInput(ctx context.Context, arg InsertTransactionInputParams) error {
	_, err := q.exec(ctx, q.insertTransactionInputStmt, InsertTransactionInput,
		arg.SpendingTxID,
		arg.InputIndex,
		arg.PrevTxHash,
		arg.PrevOutputIndex,
	)
	return err
}

const ListMinedTransactionsForward = `-- name: ListMinedTransactionsForward :many
SELECT t.id, t.wallet_id, t.tx_hash, t.raw_tx, t.received_unix,
       t.block_height, t.confirmed_order, t.is_coinbase,
       b.header_hash, b.block_timestamp
FROM transactions AS t
INNER JOIN blocks AS b ON b.block_height = t.block_height
WHERE t.wallet_id = $1
  AND t.block_height BETWEEN $2::INTEGER
                         AND $3::INTEGER
ORDER BY t.block_height ASC, t.confirmed_order ASC
`

type ListMinedTransactionsForwardParams struct {
	WalletID    int64
	StartHeight int32
	EndHeight   int32
}

type ListMinedTransactionsForwardRow struct {
	ID             int64
	WalletID       int64
	TxHash         []byte
	RawTx          []byte
	ReceivedUnix   int64
	BlockHeight    sql.NullInt32
	ConfirmedOrder sql.NullInt64
	IsCoinbase     bool
	HeaderHash     []byte
	BlockTimestamp int64
}

func (q *Queries) ListMinedTransactionsForward(ctx context.Context, arg ListMinedTransactionsForwardParams) ([]ListMinedTransactionsForwardRow, error) {
	rows, err := q.query(ctx, q.listMinedTransactionsForwardStmt, ListMinedTransactionsForward, arg.WalletID, arg.StartHeight, arg.EndHeight)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMinedTransactionsForwardRow
	for rows.Next() {
		var i ListMinedTransactionsForwardRow
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.TxHash,
			&i.RawTx,
			&i.ReceivedUnix,
			&i.BlockHeight,
			&i.ConfirmedOrder,
			&i.IsCoinbase,
			&i.HeaderHash,
			&i.BlockTimestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListMinedTransactionsReverse = `-- name: ListMinedTransactionsReverse :many
SELECT t.id, t.wallet_id, t.tx_hash, t.raw_tx, t.received_unix,
       t.block_height, t.confirmed_order, t.is_coinbase,
       b.header_hash, b.block_timestamp
FROM transactions AS t
INNER JOIN blocks AS b ON b.block_height = t.block_height
WHERE t.wallet_id = $1
  AND t.block_height BETWEEN $2::INTEGER
                         AND $3::INTEGER
ORDER BY t.block_height DESC, t.confirmed_order ASC
`

type ListMinedTransactionsReverseParams struct {
	WalletID    int64
	EndHeight   int32
	StartHeight int32
}

type ListMinedTransactionsReverseRow struct {
	ID             int64
	WalletID       int64
	TxHash         []byte
	RawTx          []byte
	ReceivedUnix   int64
	BlockHeight    sql.NullInt32
	ConfirmedOrder sql.NullInt64
	IsCoinbase     bool
	HeaderHash     []byte
	BlockTimestamp int64
}

func (q *Queries) ListMinedTransactionsReverse(ctx context.Context, arg ListMinedTransactionsReverseParams) ([]ListMinedTransactionsReverseRow, error) {
	rows, err := q.query(ctx, q.listMinedTransactionsReverseStmt, ListMinedTransactionsReverse, arg.WalletID, arg.EndHeight, arg.StartHeight)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMinedTransactionsReverseRow
	for rows.Next() {
		var i ListMinedTransactionsReverseRow
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.TxHash,
			&i.RawTx,
			&i.ReceivedUnix,
			&i.BlockHeight,
			&i.ConfirmedOrder,
			&i.IsCoinbase,
			&i.HeaderHash,
			&i.BlockTimestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTransactionIncidencesByHash = `-- name: ListTransactionIncidencesByHash :many
SELECT id, wallet_id, tx_hash, raw_tx, received_unix, block_height,
       confirmed_order, is_coinbase
FROM transactions
WHERE wallet_id = $1 AND tx_hash = $2
ORDER BY block_height NULLS FIRST, block_height DESC, id DESC
`

type ListTransactionIncidencesByHashParams struct {
	WalletID int64
	TxHash   []byte
}

func (q *Queries) ListTransactionIncidencesByHash(ctx context.Context, arg ListTransactionIncidencesByHashParams) ([]Transaction, error) {
	rows, err := q.query(ctx, q.listTransactionIncidencesByHashStmt, ListTransactionIncidencesByHash, arg.WalletID, arg.TxHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.TxHash,
			&i.RawTx,
			&i.ReceivedUnix,
			&i.BlockHeight,
			&i.ConfirmedOrder,
			&i.IsCoinbase,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUnminedSpenders = `-- name: ListUnminedSpenders :many
SELECT t.id, t.tx_hash, i.input_index
FROM transaction_inputs AS i
INNER JOIN transactions AS t ON t.id = i.spending_tx_id
WHERE t.wallet_id = $1
  AND t.block_height IS NULL
  AND i.prev_tx_hash = $2
  AND i.prev_output_index = $3
ORDER BY t.tx_hash, i.input_index
`

type ListUnminedSpendersParams struct {
	WalletID        int64
	PrevTxHash      []byte
	PrevOutputIndex int64
}

type ListUnminedSpendersRow struct {
	ID         int64
	TxHash     []byte
	InputIndex int64
}

func (q *Queries) ListUnminedSpenders(ctx context.Context, arg ListUnminedSpendersParams) ([]ListUnminedSpendersRow, error) {
	rows, err := q.query(ctx, q.listUnminedSpendersStmt, ListUnminedSpenders, arg.WalletID, arg.PrevTxHash, arg.PrevOutputIndex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnminedSpendersRow
	for rows.Next() {
		var i ListUnminedSpendersRow
		if err := rows.Scan(&i.ID, &i.TxHash, &i.InputIndex); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUnminedTransactions = `-- name: ListUnminedTransactions :many
SELECT id, wallet_id, tx_hash, raw_tx, received_unix, block_height,
       confirmed_order, is_coinbase
FROM transactions
WHERE wallet_id = $1 AND block_height IS NULL
ORDER BY tx_hash
`

func (q *Queries) ListUnminedTransactions(ctx context.Context, walletID int64) ([]Transaction, error) {
	rows, err := q.query(ctx, q.listUnminedTransactionsStmt, ListUnminedTransactions, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.TxHash,
			&i.RawTx,
			&i.ReceivedUnix,
			&i.BlockHeight,
			&i.ConfirmedOrder,
			&i.IsCoinbase,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const PromoteUnminedTransaction = `-- name: PromoteUnminedTransaction :execrows
UPDATE transactions
SET block_height = $1, confirmed_order = $2
WHERE wallet_id = $3 AND tx_hash = $4 AND block_height IS NULL
`

type PromoteUnminedTransactionParams struct {
	BlockHeight    sql.NullInt32
	ConfirmedOrder sql.NullInt64
	WalletID       int64
	TxHash         []byte
}

func (q *Queries) PromoteUnminedTransaction(ctx context.Context, arg PromoteUnminedTransactionParams) (int64, error) {
	result, err := q.exec(ctx, q.promoteUnminedTransactionStmt, PromoteUnminedTransaction,
		arg.BlockHeight,
		arg.ConfirmedOrder,
		arg.WalletID,
		arg.TxHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const PutTransactionLabel = `-- name: PutTransactionLabel :exec
INSERT INTO transaction_labels (wallet_id, tx_hash, label)
VALUES ($1, $2, $3)
ON CONFLICT (wallet_id, tx_hash) DO UPDATE SET label = excluded.label
`

type PutTransactionLabelParams struct {
	WalletID int64
	TxHash   []byte
	Label    []byte
}

func (q *Queries) PutTransactionLabel(ctx context.Context, arg PutTransactionLabelParams) error {
	_, err := q.exec(ctx, q.putTransactionLabelStmt, PutTransactionLabel, arg.WalletID, arg.TxHash, arg.Label)
	return err
}
