// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallets.sql

package sqlc

import (
	"context"
	"database/sql"
)

const AdvanceWalletSyncedTo = `-- name: AdvanceWalletSyncedTo :execrows
UPDATE wallet_sync_states
SET synced_block_id =
    (SELECT nb.id FROM blocks AS nb WHERE nb.header_hash = $1)
WHERE wallet_id = $2
    AND synced_block_id =
        (SELECT eb.id FROM blocks AS eb WHERE eb.header_hash = $3)
`

type AdvanceWalletSyncedToParams struct {
	NewBlockHash      []byte
	WalletID          int64
	ExpectedBlockHash []byte
}

// AdvanceWalletSyncedTo advances the wallet's synced block to new_block_hash,
// but only while the current synced block still equals expected_block_hash, so a
// tip advance is an optimistic compare-and-swap. The new block must already
// exist. Zero affected rows means the caller's expected tip was stale and no
// advance was made.
func (q *Queries) AdvanceWalletSyncedTo(ctx context.Context, arg AdvanceWalletSyncedToParams) (int64, error) {
	result, err := q.exec(ctx, q.advanceWalletSyncedToStmt, AdvanceWalletSyncedTo, arg.NewBlockHash, arg.WalletID, arg.ExpectedBlockHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const CreateWallet = `-- name: CreateWallet :one
INSERT INTO wallets (
    wallet_name,
    manager_version,
    manager_created_at,
    is_watch_only,
    master_pub_params,
    master_priv_params,
    encrypted_crypto_pub_key,
    encrypted_crypto_priv_key,
    encrypted_crypto_script_key,
    encrypted_master_hd_pub_key,
    encrypted_master_hd_priv_key
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id
`

type CreateWalletParams struct {
	WalletName               string
	ManagerVersion           int64
	ManagerCreatedAt         int64
	IsWatchOnly              bool
	MasterPubParams          []byte
	MasterPrivParams         []byte
	EncryptedCryptoPubKey    []byte
	EncryptedCryptoPrivKey   []byte
	EncryptedCryptoScriptKey []byte
	EncryptedMasterHdPubKey  []byte
	EncryptedMasterHdPrivKey []byte
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (int64, error) {
	row := q.queryRow(ctx, q.createWalletStmt, CreateWallet,
		arg.WalletName,
		arg.ManagerVersion,
		arg.ManagerCreatedAt,
		arg.IsWatchOnly,
		arg.MasterPubParams,
		arg.MasterPrivParams,
		arg.EncryptedCryptoPubKey,
		arg.EncryptedCryptoPrivKey,
		arg.EncryptedCryptoScriptKey,
		arg.EncryptedMasterHdPubKey,
		arg.EncryptedMasterHdPrivKey,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const DeleteManagerPrivateKeys = `-- name: DeleteManagerPrivateKeys :execrows
UPDATE wallets
SET
    master_priv_params = NULL,
    encrypted_crypto_priv_key = NULL,
    encrypted_crypto_script_key = NULL,
    encrypted_master_hd_priv_key = NULL
WHERE id = $1
`

func (q *Queries) DeleteManagerPrivateKeys(ctx context.Context, id int64) (int64, error) {
	result, err := q.exec(ctx, q.deleteManagerPrivateKeysStmt, DeleteManagerPrivateKeys, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const GetManagerState = `-- name: GetManagerState :one
SELECT
    manager_version,
    manager_created_at,
    is_watch_only,
    master_pub_params,
    master_priv_params,
    encrypted_crypto_pub_key,
    encrypted_crypto_priv_key,
    encrypted_crypto_script_key,
    encrypted_master_hd_pub_key,
    encrypted_master_hd_priv_key
FROM wallets
WHERE id = $1
`

type GetManagerStateRow struct {
	ManagerVersion           int64
	ManagerCreatedAt         int64
	IsWatchOnly              bool
	MasterPubParams          []byte
	MasterPrivParams         []byte
	EncryptedCryptoPubKey    []byte
	EncryptedCryptoPrivKey   []byte
	EncryptedCryptoScriptKey []byte
	EncryptedMasterHdPubKey  []byte
	EncryptedMasterHdPrivKey []byte
}

func (q *Queries) GetManagerState(ctx context.Context, id int64) (GetManagerStateRow, error) {
	row := q.queryRow(ctx, q.getManagerStateStmt, GetManagerState, id)
	var i GetManagerStateRow
	err := row.Scan(
		&i.ManagerVersion,
		&i.ManagerCreatedAt,
		&i.IsWatchOnly,
		&i.MasterPubParams,
		&i.MasterPrivParams,
		&i.EncryptedCryptoPubKey,
		&i.EncryptedCryptoPrivKey,
		&i.EncryptedCryptoScriptKey,
		&i.EncryptedMasterHdPubKey,
		&i.EncryptedMasterHdPrivKey,
	)
	return i, err
}

const GetWalletByName = `-- name: GetWalletByName :one
SELECT
    id,
    wallet_name,
    manager_version,
    manager_created_at,
    is_watch_only,
    master_pub_params,
    master_priv_params,
    encrypted_crypto_pub_key,
    encrypted_crypto_priv_key,
    encrypted_crypto_script_key,
    encrypted_master_hd_pub_key,
    encrypted_master_hd_priv_key
FROM wallets
WHERE wallet_name = $1
`

func (q *Queries) GetWalletByName(ctx context.Context, walletName string) (Wallet, error) {
	row := q.queryRow(ctx, q.getWalletByNameStmt, GetWalletByName, walletName)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.WalletName,
		&i.ManagerVersion,
		&i.ManagerCreatedAt,
		&i.IsWatchOnly,
		&i.MasterPubParams,
		&i.MasterPrivParams,
		&i.EncryptedCryptoPubKey,
		&i.EncryptedCryptoPrivKey,
		&i.EncryptedCryptoScriptKey,
		&i.EncryptedMasterHdPubKey,
		&i.EncryptedMasterHdPrivKey,
	)
	return i, err
}

const GetWalletStartBlock = `-- name: GetWalletStartBlock :one
SELECT b.block_height, b.header_hash, b.block_timestamp
FROM wallet_sync_states AS s
INNER JOIN blocks AS b ON b.id = s.start_block_id
WHERE s.wallet_id = $1
`

type GetWalletStartBlockRow struct {
	BlockHeight    int32
	HeaderHash     []byte
	BlockTimestamp int64
}

func (q *Queries) GetWalletStartBlock(ctx context.Context, walletID int64) (GetWalletStartBlockRow, error) {
	row := q.queryRow(ctx, q.getWalletStartBlockStmt, GetWalletStartBlock, walletID)
	var i GetWalletStartBlockRow
	err := row.Scan(&i.BlockHeight, &i.HeaderHash, &i.BlockTimestamp)
	return i, err
}

const GetWalletSyncState = `-- name: GetWalletSyncState :one
SELECT
    s.wallet_id,
    start_block.block_height AS start_block_height,
    start_block.header_hash AS start_block_hash,
    start_block.block_timestamp AS start_block_timestamp,
    synced_block.block_height AS synced_block_height,
    synced_block.header_hash AS synced_block_hash,
    synced_block.block_timestamp AS synced_block_timestamp,
    s.birthday_timestamp,
    birthday_block.block_height AS birthday_block_height,
    birthday_block.header_hash AS birthday_block_hash,
    birthday_block.block_timestamp AS birthday_block_timestamp,
    s.birthday_block_verified
FROM wallet_sync_states AS s
INNER JOIN blocks AS start_block
    ON start_block.id = s.start_block_id
INNER JOIN blocks AS synced_block
    ON synced_block.id = s.synced_block_id
LEFT JOIN blocks AS birthday_block
    ON birthday_block.id = s.birthday_block_id
WHERE s.wallet_id = $1
`

type GetWalletSyncStateRow struct {
	WalletID               int64
	StartBlockHeight       int32
	StartBlockHash         []byte
	StartBlockTimestamp    int64
	SyncedBlockHeight      int32
	SyncedBlockHash        []byte
	SyncedBlockTimestamp   int64
	BirthdayTimestamp      int64
	BirthdayBlockHeight    sql.NullInt32
	BirthdayBlockHash      []byte
	BirthdayBlockTimestamp sql.NullInt64
	BirthdayBlockVerified  bool
}

func (q *Queries) GetWalletSyncState(ctx context.Context, walletID int64) (GetWalletSyncStateRow, error) {
	row := q.queryRow(ctx, q.getWalletSyncStateStmt, GetWalletSyncState, walletID)
	var i GetWalletSyncStateRow
	err := row.Scan(
		&i.WalletID,
		&i.StartBlockHeight,
		&i.StartBlockHash,
		&i.StartBlockTimestamp,
		&i.SyncedBlockHeight,
		&i.SyncedBlockHash,
		&i.SyncedBlockTimestamp,
		&i.BirthdayTimestamp,
		&i.BirthdayBlockHeight,
		&i.BirthdayBlockHash,
		&i.BirthdayBlockTimestamp,
		&i.BirthdayBlockVerified,
	)
	return i, err
}

const PutManagerState = `-- name: PutManagerState :execrows
UPDATE wallets
SET
    manager_version = $1,
    manager_created_at = $2,
    is_watch_only = $3,
    master_pub_params = $4,
    master_priv_params = $5,
    encrypted_crypto_pub_key = $6,
    encrypted_crypto_priv_key = $7,
    encrypted_crypto_script_key = $8,
    encrypted_master_hd_pub_key = $9,
    encrypted_master_hd_priv_key = $10
WHERE id = $11
`

type PutManagerStateParams struct {
	ManagerVersion           int64
	ManagerCreatedAt         int64
	IsWatchOnly              bool
	MasterPubParams          []byte
	MasterPrivParams         []byte
	EncryptedCryptoPubKey    []byte
	EncryptedCryptoPrivKey   []byte
	EncryptedCryptoScriptKey []byte
	EncryptedMasterHdPubKey  []byte
	EncryptedMasterHdPrivKey []byte
	ID                       int64
}

func (q *Queries) PutManagerState(ctx context.Context, arg PutManagerStateParams) (int64, error) {
	result, err := q.exec(ctx, q.putManagerStateStmt, PutManagerState,
		arg.ManagerVersion,
		arg.ManagerCreatedAt,
		arg.IsWatchOnly,
		arg.MasterPubParams,
		arg.MasterPrivParams,
		arg.EncryptedCryptoPubKey,
		arg.EncryptedCryptoPrivKey,
		arg.EncryptedCryptoScriptKey,
		arg.EncryptedMasterHdPubKey,
		arg.EncryptedMasterHdPrivKey,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const PutWalletSyncState = `-- name: PutWalletSyncState :exec
INSERT INTO wallet_sync_states (
    wallet_id,
    start_block_id,
    synced_block_id,
    birthday_timestamp,
    birthday_block_id,
    birthday_block_verified
) VALUES (
    $1,
    (SELECT sb.id FROM blocks AS sb WHERE sb.header_hash = $2),
    (SELECT yb.id FROM blocks AS yb WHERE yb.header_hash = $3),
    $4,
    (SELECT bb.id FROM blocks AS bb WHERE bb.header_hash = $5),
    $6
)
`

type PutWalletSyncStateParams struct {
	WalletID              int64
	StartBlockHash        []byte
	SyncedBlockHash       []byte
	BirthdayTimestamp     int64
	BirthdayBlockHash     []byte
	BirthdayBlockVerified bool
}

// Block references resolve from the globally unique header hash, so the blocks
// must already exist before this insert runs.
func (q *Queries) PutWalletSyncState(ctx context.Context, arg PutWalletSyncStateParams) error {
	_, err := q.exec(ctx, q.putWalletSyncStateStmt, PutWalletSyncState,
		arg.WalletID,
		arg.StartBlockHash,
		arg.SyncedBlockHash,
		arg.BirthdayTimestamp,
		arg.BirthdayBlockHash,
		arg.BirthdayBlockVerified,
	)
	return err
}

const SetWalletBirthday = `-- name: SetWalletBirthday :execrows
UPDATE wallet_sync_states
SET birthday_timestamp = $1
WHERE wallet_id = $2
`

type SetWalletBirthdayParams struct {
	BirthdayTimestamp int64
	WalletID          int64
}

func (q *Queries) SetWalletBirthday(ctx context.Context, arg SetWalletBirthdayParams) (int64, error) {
	result, err := q.exec(ctx, q.setWalletBirthdayStmt, SetWalletBirthday, arg.BirthdayTimestamp, arg.WalletID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const SetWalletBirthdayBlock = `-- name: SetWalletBirthdayBlock :execrows
UPDATE wallet_sync_states
SET birthday_block_id =
    (SELECT id FROM blocks WHERE header_hash = $1)
WHERE wallet_id = $2
`

type SetWalletBirthdayBlockParams struct {
	BlockHash []byte
	WalletID  int64
}

func (q *Queries) SetWalletBirthdayBlock(ctx context.Context, arg SetWalletBirthdayBlockParams) (int64, error) {
	result, err := q.exec(ctx, q.setWalletBirthdayBlockStmt, SetWalletBirthdayBlock, arg.BlockHash, arg.WalletID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const SetWalletBirthdayBlockVerified = `-- name: SetWalletBirthdayBlockVerified :execrows
UPDATE wallet_sync_states
SET birthday_block_verified = $1
WHERE wallet_id = $2
`

type SetWalletBirthdayBlockVerifiedParams struct {
	BirthdayBlockVerified bool
	WalletID              int64
}

func (q *Queries) SetWalletBirthdayBlockVerified(ctx context.Context, arg SetWalletBirthdayBlockVerifiedParams) (int64, error) {
	result, err := q.exec(ctx, q.setWalletBirthdayBlockVerifiedStmt, SetWalletBirthdayBlockVerified, arg.BirthdayBlockVerified, arg.WalletID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const SetWalletSyncedTo = `-- name: SetWalletSyncedTo :execrows
UPDATE wallet_sync_states
SET synced_block_id =
    (SELECT id FROM blocks WHERE header_hash = $1)
WHERE wallet_id = $2
`

type SetWalletSyncedToParams struct {
	BlockHash []byte
	WalletID  int64
}

func (q *Queries) SetWalletSyncedTo(ctx context.Context, arg SetWalletSyncedToParams) (int64, error) {
	result, err := q.exec(ctx, q.setWalletSyncedToStmt, SetWalletSyncedTo, arg.BlockHash, arg.WalletID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const UpdateWalletEncryption = `-- name: UpdateWalletEncryption :execrows
UPDATE wallets
SET
    master_pub_params = $1,
    master_priv_params = $2,
    encrypted_crypto_pub_key = $3,
    encrypted_crypto_priv_key = $4,
    encrypted_crypto_script_key = $5,
    encrypted_master_hd_pub_key = $6,
    encrypted_master_hd_priv_key = $7
WHERE id = $8
`

type UpdateWalletEncryptionParams struct {
	MasterPubParams          []byte
	MasterPrivParams         []byte
	EncryptedCryptoPubKey    []byte
	EncryptedCryptoPrivKey   []byte
	EncryptedCryptoScriptKey []byte
	EncryptedMasterHdPubKey  []byte
	EncryptedMasterHdPrivKey []byte
	ID                       int64
}

func (q *Queries) UpdateWalletEncryption(ctx context.Context, arg UpdateWalletEncryptionParams) (int64, error) {
	result, err := q.exec(ctx, q.updateWalletEncryptionStmt, UpdateWalletEncryption,
		arg.MasterPubParams,
		arg.MasterPrivParams,
		arg.EncryptedCryptoPubKey,
		arg.EncryptedCryptoPrivKey,
		arg.EncryptedCryptoScriptKey,
		arg.EncryptedMasterHdPubKey,
		arg.EncryptedMasterHdPrivKey,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const UpdateWalletSyncState = `-- name: UpdateWalletSyncState :execrows
UPDATE wallet_sync_states
SET
    start_block_id =
        (SELECT sb.id FROM blocks AS sb WHERE sb.header_hash = $1),
    synced_block_id =
        (SELECT yb.id FROM blocks AS yb WHERE yb.header_hash = $2),
    birthday_timestamp = $3,
    birthday_block_id =
        (SELECT bb.id FROM blocks AS bb WHERE bb.header_hash = $4),
    birthday_block_verified = $5
WHERE wallet_id = $6
`

type UpdateWalletSyncStateParams struct {
	StartBlockHash        []byte
	SyncedBlockHash       []byte
	BirthdayTimestamp     int64
	BirthdayBlockHash     []byte
	BirthdayBlockVerified bool
	WalletID              int64
}

func (q *Queries) UpdateWalletSyncState(ctx context.Context, arg UpdateWalletSyncStateParams) (int64, error) {
	result, err := q.exec(ctx, q.updateWalletSyncStateStmt, UpdateWalletSyncState,
		arg.StartBlockHash,
		arg.SyncedBlockHash,
		arg.BirthdayTimestamp,
		arg.BirthdayBlockHash,
		arg.BirthdayBlockVerified,
		arg.WalletID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
