// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const AccountBalance = `-- name: AccountBalance :one
SELECT
    cast(coalesce(sum(
        CASE
            WHEN
                t.block_height IS NOT NULL
                AND s.synced_height IS NOT NULL
                AND t.block_height <= s.synced_height
                THEN u.amount
            ELSE 0
        END
    ), 0) AS INTEGER) AS confirmed_balance,
    cast(coalesce(sum(
        CASE
            WHEN
                t.block_height IS NULL
                OR s.synced_height IS NULL
                OR t.block_height > s.synced_height
                THEN u.amount
            ELSE 0
        END
    ), 0) AS INTEGER) AS unconfirmed_balance
FROM utxos AS u
INNER JOIN transactions AS t ON u.tx_id = t.id
INNER JOIN addresses AS addr ON u.address_id = addr.id
LEFT JOIN wallet_sync_states AS s ON t.wallet_id = s.wallet_id
WHERE
    addr.wallet_id = ?1
    AND addr.account_id = ?2
    AND u.spent_by_tx_id IS NULL
    AND t.tx_status IN (0, 1)
`

type AccountBalanceParams struct {
	WalletID  int64
	AccountID sql.NullInt64
}

type AccountBalanceRow struct {
	ConfirmedBalance   int64
	UnconfirmedBalance int64
}

// AccountBalance returns the confirmed/unconfirmed balance for one
// account, summed from the wallet's UTXO set at read time. Confirmed
// means the funding tx is in a block at or below the wallet's synced
// height; unconfirmed covers unmined and above-synced-tip outputs.
// Spent outputs (`u.spent_by_tx_id IS NOT NULL`) are excluded.
func (q *Queries) AccountBalance(ctx context.Context, arg AccountBalanceParams) (AccountBalanceRow, error) {
	row := q.queryRow(ctx, q.accountBalanceStmt, AccountBalance, arg.WalletID, arg.AccountID)
	var i AccountBalanceRow
	err := row.Scan(&i.ConfirmedBalance, &i.UnconfirmedBalance)
	return i, err
}

const AccountBalancesByIDs = `-- name: AccountBalancesByIDs :many
SELECT
    addr.account_id,
    cast(coalesce(sum(
        CASE
            WHEN
                t.block_height IS NOT NULL
                AND s.synced_height IS NOT NULL
                AND t.block_height <= s.synced_height
                THEN u.amount
            ELSE 0
        END
    ), 0) AS INTEGER) AS confirmed_balance,
    cast(coalesce(sum(
        CASE
            WHEN
                t.block_height IS NULL
                OR s.synced_height IS NULL
                OR t.block_height > s.synced_height
                THEN u.amount
            ELSE 0
        END
    ), 0) AS INTEGER) AS unconfirmed_balance
FROM utxos AS u
INNER JOIN transactions AS t ON u.tx_id = t.id
INNER JOIN addresses AS addr ON u.address_id = addr.id
LEFT JOIN wallet_sync_states AS s ON t.wallet_id = s.wallet_id
WHERE
    addr.wallet_id = ?1
    AND addr.account_id IN (/*SLICE:account_ids*/?)
    AND u.spent_by_tx_id IS NULL
    AND t.tx_status IN (0, 1)
GROUP BY addr.account_id
`

type AccountBalancesByIDsParams struct {
	WalletID   int64
	AccountIds []sql.NullInt64
}

type AccountBalancesByIDsRow struct {
	AccountID          sql.NullInt64
	ConfirmedBalance   int64
	UnconfirmedBalance int64
}

// AccountBalancesByIDs returns the confirmed/unconfirmed balance for each
// account in account_ids that has funded UTXOs, grouped by account_id. Accounts with no
// spendable outputs do not appear in the result; the Go caller defaults
// missing entries to zero. The confirmation predicate matches
// AccountBalance.
func (q *Queries) AccountBalancesByIDs(ctx context.Context, arg AccountBalancesByIDsParams) ([]AccountBalancesByIDsRow, error) {
	query := AccountBalancesByIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.WalletID)
	if len(arg.AccountIds) > 0 {
		for _, v := range arg.AccountIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:account_ids*/?", strings.Repeat(",?", len(arg.AccountIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:account_ids*/?", "NULL", 1)
	}
	rows, err := q.query(ctx, nil, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountBalancesByIDsRow
	for rows.Next() {
		var i AccountBalancesByIDsRow
		if err := rows.Scan(&i.AccountID, &i.ConfirmedBalance, &i.UnconfirmedBalance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const CreateAccountSecret = `-- name: CreateAccountSecret :exec
INSERT INTO account_secrets (
    account_id,
    encrypted_private_key
) VALUES (
    ?, ?
)
`

type CreateAccountSecretParams struct {
	AccountID           int64
	EncryptedPrivateKey []byte
}

// Inserts the encrypted private key material for an account.
func (q *Queries) CreateAccountSecret(ctx context.Context, arg CreateAccountSecretParams) error {
	_, err := q.exec(ctx, q.createAccountSecretStmt, CreateAccountSecret, arg.AccountID, arg.EncryptedPrivateKey)
	return err
}

const CreateDerivedAccount = `-- name: CreateDerivedAccount :one
INSERT INTO accounts (
    wallet_id,
    scope_id,
    account_number,
    account_name,
    origin_id,
    public_key,
    master_fingerprint
)
SELECT
    ks.wallet_id,
    ks.id AS scope_id,
    ?1 AS account_number,
    ?2 AS account_name,
    ?3 AS origin_id,
    ?4 AS public_key,
    ?5 AS master_fingerprint
FROM key_scopes AS ks
WHERE ks.id = ?6
RETURNING id, account_number, created_at
`

type CreateDerivedAccountParams struct {
	AccountNumber     sql.NullInt64
	AccountName       string
	OriginID          int64
	PublicKey         []byte
	MasterFingerprint sql.NullInt64
	ScopeID           int64
}

type CreateDerivedAccountRow struct {
	ID            int64
	AccountNumber sql.NullInt64
	CreatedAt     time.Time
}

// Creates a new derived account under the given scope using a separately
// allocated account number.
func (q *Queries) CreateDerivedAccount(ctx context.Context, arg CreateDerivedAccountParams) (CreateDerivedAccountRow, error) {
	row := q.queryRow(ctx, q.createDerivedAccountStmt, CreateDerivedAccount,
		arg.AccountNumber,
		arg.AccountName,
		arg.OriginID,
		arg.PublicKey,
		arg.MasterFingerprint,
		arg.ScopeID,
	)
	var i CreateDerivedAccountRow
	err := row.Scan(&i.ID, &i.AccountNumber, &i.CreatedAt)
	return i, err
}

const CreateDerivedAccountWithNumber = `-- name: CreateDerivedAccountWithNumber :one
INSERT INTO accounts (
    wallet_id,
    scope_id,
    account_number,
    account_name,
    origin_id
)
SELECT
    ks.wallet_id,
    ks.id AS scope_id,
    ?1 AS account_number,
    ?2 AS account_name,
    ?3 AS origin_id
FROM key_scopes AS ks
WHERE ks.id = ?4
RETURNING id, account_number, created_at
`

type CreateDerivedAccountWithNumberParams struct {
	AccountNumber sql.NullInt64
	AccountName   string
	OriginID      int64
	ScopeID       int64
}

type CreateDerivedAccountWithNumberRow struct {
	ID            int64
	AccountNumber sql.NullInt64
	CreatedAt     time.Time
}

// Test-only: Creates a derived account with a specific account number.
// Used for testing account number overflow without creating billions of accounts.
func (q *Queries) CreateDerivedAccountWithNumber(ctx context.Context, arg CreateDerivedAccountWithNumberParams) (CreateDerivedAccountWithNumberRow, error) {
	row := q.queryRow(ctx, q.createDerivedAccountWithNumberStmt, CreateDerivedAccountWithNumber,
		arg.AccountNumber,
		arg.AccountName,
		arg.OriginID,
		arg.ScopeID,
	)
	var i CreateDerivedAccountWithNumberRow
	err := row.Scan(&i.ID, &i.AccountNumber, &i.CreatedAt)
	return i, err
}

const CreateImportedAccount = `-- name: CreateImportedAccount :one
INSERT INTO accounts (
    wallet_id,
    scope_id,
    account_number,
    account_name,
    origin_id,
    public_key,
    master_fingerprint
)
SELECT
    ks.wallet_id,
    ks.id AS scope_id,
    NULL AS account_number,
    ?1 AS account_name,
    ?2 AS origin_id,
    ?3 AS public_key,
    ?4 AS master_fingerprint
FROM key_scopes AS ks
WHERE ks.id = ?5
RETURNING id, created_at
`

type CreateImportedAccountParams struct {
	AccountName       string
	OriginID          int64
	PublicKey         []byte
	MasterFingerprint sql.NullInt64
	ScopeID           int64
}

type CreateImportedAccountRow struct {
	ID        int64
	CreatedAt time.Time
}

// Creates a new imported account under the given scope with NULL account
// number. Imported accounts don't follow BIP44 derivation, so they don't need
// a sequential account number.
func (q *Queries) CreateImportedAccount(ctx context.Context, arg CreateImportedAccountParams) (CreateImportedAccountRow, error) {
	row := q.queryRow(ctx, q.createImportedAccountStmt, CreateImportedAccount,
		arg.AccountName,
		arg.OriginID,
		arg.PublicKey,
		arg.MasterFingerprint,
		arg.ScopeID,
	)
	var i CreateImportedAccountRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const CreateImportedBucketAccount = `-- name: CreateImportedBucketAccount :exec
INSERT INTO accounts (
    wallet_id,
    scope_id,
    account_number,
    account_name,
    origin_id
)
SELECT
    ks.wallet_id,
    ks.id AS scope_id,
    NULL AS account_number,
    ?1 AS account_name,
    ?2 AS origin_id
FROM key_scopes AS ks
WHERE ks.id = ?3
ON CONFLICT (scope_id, account_name) DO NOTHING
`

type CreateImportedBucketAccountParams struct {
	AccountName string
	OriginID    int64
	ScopeID     int64
}

// Materializes the keyless wallet-level imported "bucket" account for a scope.
// The bucket holds individually-imported addresses and carries no
// account-level key material. ON CONFLICT DO NOTHING makes the insert an
// idempotent get-or-create: concurrent first-imports into the same scope each
// attempt this insert, one wins and the rest are no-ops, so callers re-read the
// bucket instead of colliding on the (scope_id, account_name) unique index.
func (q *Queries) CreateImportedBucketAccount(ctx context.Context, arg CreateImportedBucketAccountParams) error {
	_, err := q.exec(ctx, q.createImportedBucketAccountStmt, CreateImportedBucketAccount, arg.AccountName, arg.OriginID, arg.ScopeID)
	return err
}

const GetAccountByScopeAndName = `-- name: GetAccountByScopeAndName :one
SELECT
    a.id,
    a.account_number,
    a.account_name,
    a.origin_id,
    a.created_at,
    ks.purpose,
    ks.coin_type,
    ks.internal_type_id,
    ks.external_type_id,
    a.next_external_index AS external_key_count,
    a.next_internal_index AS internal_key_count,
    a.imported_key_count,
    a.public_key,
    a.master_fingerprint,
    w.is_watch_only AS wallet_is_watch_only
FROM accounts AS a
INNER JOIN key_scopes AS ks ON a.scope_id = ks.id
INNER JOIN wallets AS w ON a.wallet_id = w.id
WHERE a.scope_id = ? AND a.account_name = ?
`

type GetAccountByScopeAndNameParams struct {
	ScopeID     int64
	AccountName string
}

type GetAccountByScopeAndNameRow struct {
	ID                int64
	AccountNumber     sql.NullInt64
	AccountName       string
	OriginID          int64
	CreatedAt         time.Time
	Purpose           int64
	CoinType          int64
	InternalTypeID    int64
	ExternalTypeID    int64
	ExternalKeyCount  int64
	InternalKeyCount  int64
	ImportedKeyCount  int64
	PublicKey         []byte
	MasterFingerprint sql.NullInt64
	WalletIsWatchOnly bool
}

// Returns a single account by scope id and account name.
func (q *Queries) GetAccountByScopeAndName(ctx context.Context, arg GetAccountByScopeAndNameParams) (GetAccountByScopeAndNameRow, error) {
	row := q.queryRow(ctx, q.getAccountByScopeAndNameStmt, GetAccountByScopeAndName, arg.ScopeID, arg.AccountName)
	var i GetAccountByScopeAndNameRow
	err := row.Scan(
		&i.ID,
		&i.AccountNumber,
		&i.AccountName,
		&i.OriginID,
		&i.CreatedAt,
		&i.Purpose,
		&i.CoinType,
		&i.InternalTypeID,
		&i.ExternalTypeID,
		&i.ExternalKeyCount,
		&i.InternalKeyCount,
		&i.ImportedKeyCount,
		&i.PublicKey,
		&i.MasterFingerprint,
		&i.WalletIsWatchOnly,
	)
	return i, err
}

const GetAccountByScopeAndNumber = `-- name: GetAccountByScopeAndNumber :one
SELECT
    a.id,
    a.account_number,
    a.account_name,
    a.origin_id,
    a.created_at,
    ks.purpose,
    ks.coin_type,
    ks.internal_type_id,
    ks.external_type_id,
    a.next_external_index AS external_key_count,
    a.next_internal_index AS internal_key_count,
    a.imported_key_count,
    a.public_key,
    a.master_fingerprint,
    w.is_watch_only AS wallet_is_watch_only
FROM accounts AS a
INNER JOIN key_scopes AS ks ON a.scope_id = ks.id
INNER JOIN wallets AS w ON a.wallet_id = w.id
WHERE a.scope_id = ? AND a.account_number = ?
`

type GetAccountByScopeAndNumberParams struct {
	ScopeID       int64
	AccountNumber sql.NullInt64
}

type GetAccountByScopeAndNumberRow struct {
	ID                int64
	AccountNumber     sql.NullInt64
	AccountName       string
	OriginID          int64
	CreatedAt         time.Time
	Purpose           int64
	CoinType          int64
	InternalTypeID    int64
	ExternalTypeID    int64
	ExternalKeyCount  int64
	InternalKeyCount  int64
	ImportedKeyCount  int64
	PublicKey         []byte
	MasterFingerprint sql.NullInt64
	WalletIsWatchOnly bool
}

// Returns a single account by scope id and account number.
func (q *Queries) GetAccountByScopeAndNumber(ctx context.Context, arg GetAccountByScopeAndNumberParams) (GetAccountByScopeAndNumberRow, error) {
	row := q.queryRow(ctx, q.getAccountByScopeAndNumberStmt, GetAccountByScopeAndNumber, arg.ScopeID, arg.AccountNumber)
	var i GetAccountByScopeAndNumberRow
	err := row.Scan(
		&i.ID,
		&i.AccountNumber,
		&i.AccountName,
		&i.OriginID,
		&i.CreatedAt,
		&i.Purpose,
		&i.CoinType,
		&i.InternalTypeID,
		&i.ExternalTypeID,
		&i.ExternalKeyCount,
		&i.InternalKeyCount,
		&i.ImportedKeyCount,
		&i.PublicKey,
		&i.MasterFingerprint,
		&i.WalletIsWatchOnly,
	)
	return i, err
}

const GetAccountByWalletScopeAndName = `-- name: GetAccountByWalletScopeAndName :one
SELECT
    a.id,
    a.account_number,
    a.account_name,
    a.origin_id,
    a.created_at,
    ks.purpose,
    ks.coin_type,
    ks.internal_type_id,
    ks.external_type_id,
    a.next_external_index AS external_key_count,
    a.next_internal_index AS internal_key_count,
    a.imported_key_count,
    a.public_key,
    a.master_fingerprint,
    w.is_watch_only AS wallet_is_watch_only
FROM accounts AS a
INNER JOIN key_scopes AS ks ON a.scope_id = ks.id
INNER JOIN wallets AS w ON a.wallet_id = w.id
WHERE
    ks.wallet_id = ?
    AND ks.purpose = ?
    AND ks.coin_type = ?
    AND a.account_name = ?
`

type GetAccountByWalletScopeAndNameParams struct {
	WalletID    int64
	Purpose     int64
	CoinType    int64
	AccountName string
}

type GetAccountByWalletScopeAndNameRow struct {
	ID                int64
	AccountNumber     sql.NullInt64
	AccountName       string
	OriginID          int64
	CreatedAt         time.Time
	Purpose           int64
	CoinType          int64
	InternalTypeID    int64
	ExternalTypeID    int64
	ExternalKeyCount  int64
	InternalKeyCount  int64
	ImportedKeyCount  int64
	PublicKey         []byte
	MasterFingerprint sql.NullInt64
	WalletIsWatchOnly bool
}

// Returns a single account by wallet id, scope tuple, and account name.
func (q *Queries) GetAccountByWalletScopeAndName(ctx context.Context, arg GetAccountByWalletScopeAndNameParams) (GetAccountByWalletScopeAndNameRow, error) {
	row := q.queryRow(ctx, q.getAccountByWalletScopeAndNameStmt, GetAccountByWalletScopeAndName,
		arg.WalletID,
		arg.Purpose,
		arg.CoinType,
		arg.AccountName,
	)
	var i GetAccountByWalletScopeAndNameRow
	err := row.Scan(
		&i.ID,
		&i.AccountNumber,
		&i.AccountName,
		&i.OriginID,
		&i.CreatedAt,
		&i.Purpose,
		&i.CoinType,
		&i.InternalTypeID,
		&i.ExternalTypeID,
		&i.ExternalKeyCount,
		&i.InternalKeyCount,
		&i.ImportedKeyCount,
		&i.PublicKey,
		&i.MasterFingerprint,
		&i.WalletIsWatchOnly,
	)
	return i, err
}

const GetAccountByWalletScopeAndNumber = `-- name: GetAccountByWalletScopeAndNumber :one
SELECT
    a.id,
    a.account_number,
    a.account_name,
    a.origin_id,
    a.created_at,
    ks.purpose,
    ks.coin_type,
    ks.internal_type_id,
    ks.external_type_id,
    a.next_external_index AS external_key_count,
    a.next_internal_index AS internal_key_count,
    a.imported_key_count,
    a.public_key,
    a.master_fingerprint,
    w.is_watch_only AS wallet_is_watch_only
FROM accounts AS a
INNER JOIN key_scopes AS ks ON a.scope_id = ks.id
INNER JOIN wallets AS w ON a.wallet_id = w.id
WHERE
    ks.wallet_id = ?
    AND ks.purpose = ?
    AND ks.coin_type = ?
    AND a.account_number = ?
`

type GetAccountByWalletScopeAndNumberParams struct {
	WalletID      int64
	Purpose       int64
	CoinType      int64
	AccountNumber sql.NullInt64
}

type GetAccountByWalletScopeAndNumberRow struct {
	ID                int64
	AccountNumber     sql.NullInt64
	AccountName       string
	OriginID          int64
	CreatedAt         time.Time
	Purpose           int64
	CoinType          int64
	InternalTypeID    int64
	ExternalTypeID    int64
	ExternalKeyCount  int64
	InternalKeyCount  int64
	ImportedKeyCount  int64
	PublicKey         []byte
	MasterFingerprint sql.NullInt64
	WalletIsWatchOnly bool
}

// Returns a single account by wallet id, scope tuple, and account number.
func (q *Queries) GetAccountByWalletScopeAndNumber(ctx context.Context, arg GetAccountByWalletScopeAndNumberParams) (GetAccountByWalletScopeAndNumberRow, error) {
	row := q.queryRow(ctx, q.getAccountByWalletScopeAndNumberStmt, GetAccountByWalletScopeAndNumber,
		arg.WalletID,
		arg.Purpose,
		arg.CoinType,
		arg.AccountNumber,
	)
	var i GetAccountByWalletScopeAndNumberRow
	err := row.Scan(
		&i.ID,
		&i.AccountNumber,
		&i.AccountName,
		&i.OriginID,
		&i.CreatedAt,
		&i.Purpose,
		&i.CoinType,
		&i.InternalTypeID,
		&i.ExternalTypeID,
		&i.ExternalKeyCount,
		&i.InternalKeyCount,
		&i.ImportedKeyCount,
		&i.PublicKey,
		&i.MasterFingerprint,
		&i.WalletIsWatchOnly,
	)
	return i, err
}

const GetAccountPropsById = `-- name: GetAccountPropsById :one
SELECT
    a.account_number,
    a.account_name,
    a.origin_id,
    a.public_key,
    a.master_fingerprint,
    a.created_at,
    ks.purpose,
    ks.coin_type,
    ks.internal_type_id,
    ks.external_type_id,
    a.next_external_index AS external_key_count,
    a.next_internal_index AS internal_key_count,
    a.imported_key_count,
    w.is_watch_only AS wallet_is_watch_only
FROM accounts AS a
INNER JOIN key_scopes AS ks ON a.scope_id = ks.id
INNER JOIN wallets AS w ON a.wallet_id = w.id
WHERE a.id = ?
`

type GetAccountPropsByIdRow struct {
	AccountNumber     sql.NullInt64
	AccountName       string
	OriginID          int64
	PublicKey         []byte
	MasterFingerprint sql.NullInt64
	CreatedAt         time.Time
	Purpose           int64
	CoinType          int64
	InternalTypeID    int64
	ExternalTypeID    int64
	ExternalKeyCount  int64
	InternalKeyCount  int64
	ImportedKeyCount  int64
	WalletIsWatchOnly bool
}

// Returns full account properties by account id.
func (q *Queries) GetAccountPropsById(ctx context.Context, id int64) (GetAccountPropsByIdRow, error) {
	row := q.queryRow(ctx, q.getAccountPropsByIdStmt, GetAccountPropsById, id)
	var i GetAccountPropsByIdRow
	err := row.Scan(
		&i.AccountNumber,
		&i.AccountName,
		&i.OriginID,
		&i.PublicKey,
		&i.MasterFingerprint,
		&i.CreatedAt,
		&i.Purpose,
		&i.CoinType,
		&i.InternalTypeID,
		&i.ExternalTypeID,
		&i.ExternalKeyCount,
		&i.InternalKeyCount,
		&i.ImportedKeyCount,
		&i.WalletIsWatchOnly,
	)
	return i, err
}

const GetAndIncrementNextExternalIndex = `-- name: GetAndIncrementNextExternalIndex :one
UPDATE accounts
SET next_external_index = next_external_index + 1
WHERE id = ?
RETURNING next_external_index - 1 AS address_index
`

// Atomically gets the next external address index and increments the counter.
// Returns the current index value (before incrementing) for the address derivation.
func (q *Queries) GetAndIncrementNextExternalIndex(ctx context.Context, id int64) (int64, error) {
	row := q.queryRow(ctx, q.getAndIncrementNextExternalIndexStmt, GetAndIncrementNextExternalIndex, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const GetAndIncrementNextInternalIndex = `-- name: GetAndIncrementNextInternalIndex :one
UPDATE accounts
SET next_internal_index = next_internal_index + 1
WHERE id = ?
RETURNING next_internal_index - 1 AS address_index
`

// Atomically gets the next internal/change address index and increments the counter.
// Returns the current index value (before incrementing) for the address derivation.
func (q *Queries) GetAndIncrementNextInternalIndex(ctx context.Context, id int64) (int64, error) {
	row := q.queryRow(ctx, q.getAndIncrementNextInternalIndexStmt, GetAndIncrementNextInternalIndex, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const ListAccountsByScope = `-- name: ListAccountsByScope :many
SELECT
    a.id,
    a.account_number,
    a.account_name,
    a.origin_id,
    a.created_at,
    ks.purpose,
    ks.coin_type,
    ks.internal_type_id,
    ks.external_type_id,
    a.next_external_index AS external_key_count,
    a.next_internal_index AS internal_key_count,
    a.imported_key_count,
    a.public_key,
    a.master_fingerprint,
    w.is_watch_only AS wallet_is_watch_only
FROM accounts AS a
INNER JOIN key_scopes AS ks ON a.scope_id = ks.id
INNER JOIN wallets AS w ON a.wallet_id = w.id
WHERE a.scope_id = ?
ORDER BY a.account_number IS NULL, a.account_number
`

type ListAccountsByScopeRow struct {
	ID                int64
	AccountNumber     sql.NullInt64
	AccountName       string
	OriginID          int64
	CreatedAt         time.Time
	Purpose           int64
	CoinType          int64
	InternalTypeID    int64
	ExternalTypeID    int64
	ExternalKeyCount  int64
	InternalKeyCount  int64
	ImportedKeyCount  int64
	PublicKey         []byte
	MasterFingerprint sql.NullInt64
	WalletIsWatchOnly bool
}

// Lists all accounts in a scope, ordered by account number. Imported accounts
// (with NULL account_number) appear last.
func (q *Queries) ListAccountsByScope(ctx context.Context, scopeID int64) ([]ListAccountsByScopeRow, error) {
	rows, err := q.query(ctx, q.listAccountsByScopeStmt, ListAccountsByScope, scopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountsByScopeRow
	for rows.Next() {
		var i ListAccountsByScopeRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountNumber,
			&i.AccountName,
			&i.OriginID,
			&i.CreatedAt,
			&i.Purpose,
			&i.CoinType,
			&i.InternalTypeID,
			&i.ExternalTypeID,
			&i.ExternalKeyCount,
			&i.InternalKeyCount,
			&i.ImportedKeyCount,
			&i.PublicKey,
			&i.MasterFingerprint,
			&i.WalletIsWatchOnly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAccountsByWallet = `-- name: ListAccountsByWallet :many
SELECT
    a.id,
    a.account_number,
    a.account_name,
    a.origin_id,
    a.created_at,
    ks.purpose,
    ks.coin_type,
    ks.internal_type_id,
    ks.external_type_id,
    a.next_external_index AS external_key_count,
    a.next_internal_index AS internal_key_count,
    a.imported_key_count,
    a.public_key,
    a.master_fingerprint,
    w.is_watch_only AS wallet_is_watch_only
FROM accounts AS a
INNER JOIN key_scopes AS ks ON a.scope_id = ks.id
INNER JOIN wallets AS w ON a.wallet_id = w.id
WHERE ks.wallet_id = ?
ORDER BY a.account_number IS NULL, a.account_number
`

type ListAccountsByWalletRow struct {
	ID                int64
	AccountNumber     sql.NullInt64
	AccountName       string
	OriginID          int64
	CreatedAt         time.Time
	Purpose           int64
	CoinType          int64
	InternalTypeID    int64
	ExternalTypeID    int64
	ExternalKeyCount  int64
	InternalKeyCount  int64
	ImportedKeyCount  int64
	PublicKey         []byte
	MasterFingerprint sql.NullInt64
	WalletIsWatchOnly bool
}

// Lists all accounts for a wallet, ordered by account number. Imported
// accounts (with NULL account_number) appear last.
func (q *Queries) ListAccountsByWallet(ctx context.Context, walletID int64) ([]ListAccountsByWalletRow, error) {
	rows, err := q.query(ctx, q.listAccountsByWalletStmt, ListAccountsByWallet, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountsByWalletRow
	for rows.Next() {
		var i ListAccountsByWalletRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountNumber,
			&i.AccountName,
			&i.OriginID,
			&i.CreatedAt,
			&i.Purpose,
			&i.CoinType,
			&i.InternalTypeID,
			&i.ExternalTypeID,
			&i.ExternalKeyCount,
			&i.InternalKeyCount,
			&i.ImportedKeyCount,
			&i.PublicKey,
			&i.MasterFingerprint,
			&i.WalletIsWatchOnly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAccountsByWalletAndName = `-- name: ListAccountsByWalletAndName :many
SELECT
    a.id,
    a.account_number,
    a.account_name,
    a.origin_id,
    a.created_at,
    ks.purpose,
    ks.coin_type,
    ks.internal_type_id,
    ks.external_type_id,
    a.next_external_index AS external_key_count,
    a.next_internal_index AS internal_key_count,
    a.imported_key_count,
    a.public_key,
    a.master_fingerprint,
    w.is_watch_only AS wallet_is_watch_only
FROM accounts AS a
INNER JOIN key_scopes AS ks ON a.scope_id = ks.id
INNER JOIN wallets AS w ON a.wallet_id = w.id
WHERE ks.wallet_id = ? AND a.account_name = ?
ORDER BY a.account_number IS NULL, a.account_number
`

type ListAccountsByWalletAndNameParams struct {
	WalletID    int64
	AccountName string
}

type ListAccountsByWalletAndNameRow struct {
	ID                int64
	AccountNumber     sql.NullInt64
	AccountName       string
	OriginID          int64
	CreatedAt         time.Time
	Purpose           int64
	CoinType          int64
	InternalTypeID    int64
	ExternalTypeID    int64
	ExternalKeyCount  int64
	InternalKeyCount  int64
	ImportedKeyCount  int64
	PublicKey         []byte
	MasterFingerprint sql.NullInt64
	WalletIsWatchOnly bool
}

// Lists all accounts for a wallet filtered by account name, ordered by account
// number. Imported accounts (with NULL account_number) appear last.
func (q *Queries) ListAccountsByWalletAndName(ctx context.Context, arg ListAccountsByWalletAndNameParams) ([]ListAccountsByWalletAndNameRow, error) {
	rows, err := q.query(ctx, q.listAccountsByWalletAndNameStmt, ListAccountsByWalletAndName, arg.WalletID, arg.AccountName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountsByWalletAndNameRow
	for rows.Next() {
		var i ListAccountsByWalletAndNameRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountNumber,
			&i.AccountName,
			&i.OriginID,
			&i.CreatedAt,
			&i.Purpose,
			&i.CoinType,
			&i.InternalTypeID,
			&i.ExternalTypeID,
			&i.ExternalKeyCount,
			&i.InternalKeyCount,
			&i.ImportedKeyCount,
			&i.PublicKey,
			&i.MasterFingerprint,
			&i.WalletIsWatchOnly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAccountsByWalletScope = `-- name: ListAccountsByWalletScope :many
SELECT
    a.id,
    a.account_number,
    a.account_name,
    a.origin_id,
    a.created_at,
    ks.purpose,
    ks.coin_type,
    ks.internal_type_id,
    ks.external_type_id,
    a.next_external_index AS external_key_count,
    a.next_internal_index AS internal_key_count,
    a.imported_key_count,
    a.public_key,
    a.master_fingerprint,
    w.is_watch_only AS wallet_is_watch_only
FROM accounts AS a
INNER JOIN key_scopes AS ks ON a.scope_id = ks.id
INNER JOIN wallets AS w ON a.wallet_id = w.id
WHERE
    ks.wallet_id = ?
    AND ks.purpose = ?
    AND ks.coin_type = ?
ORDER BY a.account_number IS NULL, a.account_number
`

type ListAccountsByWalletScopeParams struct {
	WalletID int64
	Purpose  int64
	CoinType int64
}

type ListAccountsByWalletScopeRow struct {
	ID                int64
	AccountNumber     sql.NullInt64
	AccountName       string
	OriginID          int64
	CreatedAt         time.Time
	Purpose           int64
	CoinType          int64
	InternalTypeID    int64
	ExternalTypeID    int64
	ExternalKeyCount  int64
	InternalKeyCount  int64
	ImportedKeyCount  int64
	PublicKey         []byte
	MasterFingerprint sql.NullInt64
	WalletIsWatchOnly bool
}

// Lists all accounts for a wallet and scope tuple, ordered by account number.
// Imported accounts (with NULL account_number) appear last.
func (q *Queries) ListAccountsByWalletScope(ctx context.Context, arg ListAccountsByWalletScopeParams) ([]ListAccountsByWalletScopeRow, error) {
	rows, err := q.query(ctx, q.listAccountsByWalletScopeStmt, ListAccountsByWalletScope, arg.WalletID, arg.Purpose, arg.CoinType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountsByWalletScopeRow
	for rows.Next() {
		var i ListAccountsByWalletScopeRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountNumber,
			&i.AccountName,
			&i.OriginID,
			&i.CreatedAt,
			&i.Purpose,
			&i.CoinType,
			&i.InternalTypeID,
			&i.ExternalTypeID,
			&i.ExternalKeyCount,
			&i.InternalKeyCount,
			&i.ImportedKeyCount,
			&i.PublicKey,
			&i.MasterFingerprint,
			&i.WalletIsWatchOnly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateAccountNameByWalletScopeAndName = `-- name: UpdateAccountNameByWalletScopeAndName :execrows
UPDATE accounts
SET account_name = ?1
WHERE
    scope_id IN (
        SELECT key_scopes.id
        FROM key_scopes
        WHERE
            key_scopes.wallet_id = ?2
            AND key_scopes.purpose = ?3
            AND key_scopes.coin_type = ?4
    )
    AND account_name = ?5
    AND account_number IS NOT NULL
`

type UpdateAccountNameByWalletScopeAndNameParams struct {
	NewName  string
	WalletID int64
	Purpose  int64
	CoinType int64
	OldName  string
}

// Renames an account identified by wallet id, scope tuple, and current account name.
func (q *Queries) UpdateAccountNameByWalletScopeAndName(ctx context.Context, arg UpdateAccountNameByWalletScopeAndNameParams) (int64, error) {
	result, err := q.exec(ctx, q.updateAccountNameByWalletScopeAndNameStmt, UpdateAccountNameByWalletScopeAndName,
		arg.NewName,
		arg.WalletID,
		arg.Purpose,
		arg.CoinType,
		arg.OldName,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const UpdateAccountNameByWalletScopeAndNumber = `-- name: UpdateAccountNameByWalletScopeAndNumber :execrows
UPDATE accounts
SET account_name = ?1
WHERE
    scope_id IN (
        SELECT key_scopes.id
        FROM key_scopes
        WHERE
            key_scopes.wallet_id = ?2
            AND key_scopes.purpose = ?3
            AND key_scopes.coin_type = ?4
    )
    AND account_number = ?5
`

type UpdateAccountNameByWalletScopeAndNumberParams struct {
	NewName       string
	WalletID      int64
	Purpose       int64
	CoinType      int64
	AccountNumber sql.NullInt64
}

// Renames an account identified by wallet id, scope tuple, and account number.
func (q *Queries) UpdateAccountNameByWalletScopeAndNumber(ctx context.Context, arg UpdateAccountNameByWalletScopeAndNumberParams) (int64, error) {
	result, err := q.exec(ctx, q.updateAccountNameByWalletScopeAndNumberStmt, UpdateAccountNameByWalletScopeAndNumber,
		arg.NewName,
		arg.WalletID,
		arg.Purpose,
		arg.CoinType,
		arg.AccountNumber,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
