// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: database_identity.sql

package sqlc

import (
	"context"
)

const CountDatabaseIdentities = `-- name: CountDatabaseIdentities :one
SELECT count(*) AS row_count
FROM btcwallet_database_identity
`

// CountDatabaseIdentities verifies the singleton invariant before any stored
// values are trusted by startup.
func (q *Queries) CountDatabaseIdentities(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countDatabaseIdentitiesStmt, CountDatabaseIdentities)
	var row_count int64
	err := row.Scan(&row_count)
	return row_count, err
}

const GetDatabaseIdentity = `-- name: GetDatabaseIdentity :one
SELECT
    genesis_hash,
    network_magic,
    signet_challenge_digest
FROM btcwallet_database_identity
WHERE
    id = 1
    AND typeof(genesis_hash) = 'blob'
    AND length(genesis_hash) = 32
    AND typeof(network_magic) = 'integer'
    AND network_magic BETWEEN 0 AND 4294967295
    AND (
        signet_challenge_digest IS NULL
        OR (
            typeof(signet_challenge_digest) = 'blob'
            AND length(signet_challenge_digest) = 32
        )
    )
`

type GetDatabaseIdentityRow struct {
	GenesisHash           []byte
	NetworkMagic          int64
	SignetChallengeDigest []byte
}

// GetDatabaseIdentity reads only a canonical SQLite value tuple so dynamic
// storage classes and out-of-range integers become a malformed missing row.
func (q *Queries) GetDatabaseIdentity(ctx context.Context) (GetDatabaseIdentityRow, error) {
	row := q.queryRow(ctx, q.getDatabaseIdentityStmt, GetDatabaseIdentity)
	var i GetDatabaseIdentityRow
	err := row.Scan(&i.GenesisHash, &i.NetworkMagic, &i.SignetChallengeDigest)
	return i, err
}

const InsertDatabaseIdentity = `-- name: InsertDatabaseIdentity :exec
INSERT INTO btcwallet_database_identity (
    id,
    genesis_hash,
    network_magic,
    signet_challenge_digest
) VALUES (
    1,
    ?1,
    ?2,
    ?3
)
`

type InsertDatabaseIdentityParams struct {
	GenesisHash           []byte
	NetworkMagic          int64
	SignetChallengeDigest []byte
}

// InsertDatabaseIdentity writes the only permitted row after catalog checks
// prove that an unmarked SQLite file is empty and safe to claim.
func (q *Queries) InsertDatabaseIdentity(ctx context.Context, arg InsertDatabaseIdentityParams) error {
	_, err := q.exec(ctx, q.insertDatabaseIdentityStmt, InsertDatabaseIdentity, arg.GenesisHash, arg.NetworkMagic, arg.SignetChallengeDigest)
	return err
}
