// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package sqlc

import (
	"context"
	"database/sql"
)

const DeleteCreditSpendsBySpendingTx = `-- name: DeleteCreditSpendsBySpendingTx :execrows
DELETE FROM credit_spends
WHERE wallet_id = ? AND spending_tx_id = ?
`

type DeleteCreditSpendsBySpendingTxParams struct {
	WalletID     int64
	SpendingTxID int64
}

func (q *Queries) DeleteCreditSpendsBySpendingTx(ctx context.Context, arg DeleteCreditSpendsBySpendingTxParams) (int64, error) {
	result, err := q.exec(ctx, q.deleteCreditSpendsBySpendingTxStmt, DeleteCreditSpendsBySpendingTx, arg.WalletID, arg.SpendingTxID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const DeleteTransactionByID = `-- name: DeleteTransactionByID :execrows
DELETE FROM transactions WHERE wallet_id = ? AND id = ?
`

type DeleteTransactionByIDParams struct {
	WalletID int64
	ID       int64
}

func (q *Queries) DeleteTransactionByID(ctx context.Context, arg DeleteTransactionByIDParams) (int64, error) {
	result, err := q.exec(ctx, q.deleteTransactionByIDStmt, DeleteTransactionByID, arg.WalletID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const DetachMinedTransaction = `-- name: DetachMinedTransaction :execrows
UPDATE transactions
SET block_id = NULL, confirmed_order = NULL
WHERE wallet_id = ? AND id = ? AND block_id IS NOT NULL
`

type DetachMinedTransactionParams struct {
	WalletID int64
	ID       int64
}

func (q *Queries) DetachMinedTransaction(ctx context.Context, arg DetachMinedTransactionParams) (int64, error) {
	result, err := q.exec(ctx, q.detachMinedTransactionStmt, DetachMinedTransaction, arg.WalletID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const GetMinedTransactionByIncidence = `-- name: GetMinedTransactionByIncidence :one
SELECT t.id, t.wallet_id, t.tx_hash, t.raw_tx, t.received_unix,
       t.block_id, t.confirmed_order, t.is_coinbase
FROM transactions AS t
INNER JOIN blocks AS b ON b.id = t.block_id
WHERE t.wallet_id = ?1
  AND t.tx_hash = ?2
  AND b.block_height = ?3
  AND b.header_hash = ?4
`

type GetMinedTransactionByIncidenceParams struct {
	WalletID    int64
	TxHash      []byte
	BlockHeight int64
	BlockHash   []byte
}

func (q *Queries) GetMinedTransactionByIncidence(ctx context.Context, arg GetMinedTransactionByIncidenceParams) (Transaction, error) {
	row := q.queryRow(ctx, q.getMinedTransactionByIncidenceStmt, GetMinedTransactionByIncidence,
		arg.WalletID,
		arg.TxHash,
		arg.BlockHeight,
		arg.BlockHash,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.TxHash,
		&i.RawTx,
		&i.ReceivedUnix,
		&i.BlockID,
		&i.ConfirmedOrder,
		&i.IsCoinbase,
	)
	return i, err
}

const GetMinedTransactionDetails = `-- name: GetMinedTransactionDetails :one
SELECT t.id, t.raw_tx, t.received_unix, b.block_height,
       t.confirmed_order, b.header_hash, b.block_timestamp, l.label
FROM transactions AS t
INNER JOIN blocks AS b ON b.id = t.block_id
LEFT JOIN transaction_labels AS l
    ON l.wallet_id = t.wallet_id AND l.tx_hash = t.tx_hash
WHERE t.wallet_id = ?1
  AND t.tx_hash = ?2
  AND b.block_height = cast(?3 AS INTEGER)
  AND b.header_hash = ?4
LIMIT 1
`

type GetMinedTransactionDetailsParams struct {
	WalletID    int64
	TxHash      []byte
	BlockHeight int64
	BlockHash   []byte
}

type GetMinedTransactionDetailsRow struct {
	ID             int64
	RawTx          []byte
	ReceivedUnix   int64
	BlockHeight    int64
	ConfirmedOrder sql.NullInt64
	HeaderHash     []byte
	BlockTimestamp int64
	Label          []byte
}

func (q *Queries) GetMinedTransactionDetails(ctx context.Context, arg GetMinedTransactionDetailsParams) (GetMinedTransactionDetailsRow, error) {
	row := q.queryRow(ctx, q.getMinedTransactionDetailsStmt, GetMinedTransactionDetails,
		arg.WalletID,
		arg.TxHash,
		arg.BlockHeight,
		arg.BlockHash,
	)
	var i GetMinedTransactionDetailsRow
	err := row.Scan(
		&i.ID,
		&i.RawTx,
		&i.ReceivedUnix,
		&i.BlockHeight,
		&i.ConfirmedOrder,
		&i.HeaderHash,
		&i.BlockTimestamp,
		&i.Label,
	)
	return i, err
}

const GetMinedTransactionID = `-- name: GetMinedTransactionID :one
SELECT t.id
FROM transactions AS t
INNER JOIN blocks AS b ON b.id = t.block_id
WHERE t.wallet_id = ?1
  AND t.tx_hash = ?2
  AND b.block_height = cast(?3 AS INTEGER)
  AND b.header_hash = ?4
`

type GetMinedTransactionIDParams struct {
	WalletID    int64
	TxHash      []byte
	BlockHeight int64
	BlockHash   []byte
}

func (q *Queries) GetMinedTransactionID(ctx context.Context, arg GetMinedTransactionIDParams) (int64, error) {
	row := q.queryRow(ctx, q.getMinedTransactionIDStmt, GetMinedTransactionID,
		arg.WalletID,
		arg.TxHash,
		arg.BlockHeight,
		arg.BlockHash,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const GetTransactionDetailsByHash = `-- name: GetTransactionDetailsByHash :one
SELECT t.id, t.raw_tx, t.received_unix, b.block_height,
       t.confirmed_order, b.header_hash, b.block_timestamp, l.label
FROM transactions AS t
LEFT JOIN blocks AS b ON b.id = t.block_id
LEFT JOIN transaction_labels AS l
    ON l.wallet_id = t.wallet_id AND l.tx_hash = t.tx_hash
WHERE t.wallet_id = ? AND t.tx_hash = ?
ORDER BY t.block_id IS NULL DESC, b.block_height DESC, t.id DESC
LIMIT 1
`

type GetTransactionDetailsByHashParams struct {
	WalletID int64
	TxHash   []byte
}

type GetTransactionDetailsByHashRow struct {
	ID             int64
	RawTx          []byte
	ReceivedUnix   int64
	BlockHeight    sql.NullInt64
	ConfirmedOrder sql.NullInt64
	HeaderHash     []byte
	BlockTimestamp sql.NullInt64
	Label          []byte
}

func (q *Queries) GetTransactionDetailsByHash(ctx context.Context, arg GetTransactionDetailsByHashParams) (GetTransactionDetailsByHashRow, error) {
	row := q.queryRow(ctx, q.getTransactionDetailsByHashStmt, GetTransactionDetailsByHash, arg.WalletID, arg.TxHash)
	var i GetTransactionDetailsByHashRow
	err := row.Scan(
		&i.ID,
		&i.RawTx,
		&i.ReceivedUnix,
		&i.BlockHeight,
		&i.ConfirmedOrder,
		&i.HeaderHash,
		&i.BlockTimestamp,
		&i.Label,
	)
	return i, err
}

const GetTransactionDetailsByID = `-- name: GetTransactionDetailsByID :one
SELECT t.id, t.raw_tx, t.received_unix, b.block_height,
       t.confirmed_order, b.header_hash, b.block_timestamp, l.label
FROM transactions AS t
LEFT JOIN blocks AS b ON b.id = t.block_id
LEFT JOIN transaction_labels AS l
    ON l.wallet_id = t.wallet_id AND l.tx_hash = t.tx_hash
WHERE t.wallet_id = ? AND t.id = ?
LIMIT 1
`

type GetTransactionDetailsByIDParams struct {
	WalletID int64
	ID       int64
}

type GetTransactionDetailsByIDRow struct {
	ID             int64
	RawTx          []byte
	ReceivedUnix   int64
	BlockHeight    sql.NullInt64
	ConfirmedOrder sql.NullInt64
	HeaderHash     []byte
	BlockTimestamp sql.NullInt64
	Label          []byte
}

func (q *Queries) GetTransactionDetailsByID(ctx context.Context, arg GetTransactionDetailsByIDParams) (GetTransactionDetailsByIDRow, error) {
	row := q.queryRow(ctx, q.getTransactionDetailsByIDStmt, GetTransactionDetailsByID, arg.WalletID, arg.ID)
	var i GetTransactionDetailsByIDRow
	err := row.Scan(
		&i.ID,
		&i.RawTx,
		&i.ReceivedUnix,
		&i.BlockHeight,
		&i.ConfirmedOrder,
		&i.HeaderHash,
		&i.BlockTimestamp,
		&i.Label,
	)
	return i, err
}

const GetTransactionLabel = `-- name: GetTransactionLabel :one
SELECT label FROM transaction_labels WHERE wallet_id = ? AND tx_hash = ?
`

type GetTransactionLabelParams struct {
	WalletID int64
	TxHash   []byte
}

func (q *Queries) GetTransactionLabel(ctx context.Context, arg GetTransactionLabelParams) ([]byte, error) {
	row := q.queryRow(ctx, q.getTransactionLabelStmt, GetTransactionLabel, arg.WalletID, arg.TxHash)
	var label []byte
	err := row.Scan(&label)
	return label, err
}

const GetUnminedTransactionByHash = `-- name: GetUnminedTransactionByHash :one
SELECT id, wallet_id, tx_hash, raw_tx, received_unix, block_id,
       confirmed_order, is_coinbase
FROM transactions
WHERE wallet_id = ? AND tx_hash = ? AND block_id IS NULL
`

type GetUnminedTransactionByHashParams struct {
	WalletID int64
	TxHash   []byte
}

func (q *Queries) GetUnminedTransactionByHash(ctx context.Context, arg GetUnminedTransactionByHashParams) (Transaction, error) {
	row := q.queryRow(ctx, q.getUnminedTransactionByHashStmt, GetUnminedTransactionByHash, arg.WalletID, arg.TxHash)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.TxHash,
		&i.RawTx,
		&i.ReceivedUnix,
		&i.BlockID,
		&i.ConfirmedOrder,
		&i.IsCoinbase,
	)
	return i, err
}

const GetUnminedTransactionDetails = `-- name: GetUnminedTransactionDetails :one
SELECT t.id, t.raw_tx, t.received_unix, b.block_height,
       t.confirmed_order, b.header_hash, b.block_timestamp, l.label
FROM transactions AS t
LEFT JOIN blocks AS b ON b.id = t.block_id
LEFT JOIN transaction_labels AS l
    ON l.wallet_id = t.wallet_id AND l.tx_hash = t.tx_hash
WHERE t.wallet_id = ? AND t.tx_hash = ? AND t.block_id IS NULL
LIMIT 1
`

type GetUnminedTransactionDetailsParams struct {
	WalletID int64
	TxHash   []byte
}

type GetUnminedTransactionDetailsRow struct {
	ID             int64
	RawTx          []byte
	ReceivedUnix   int64
	BlockHeight    sql.NullInt64
	ConfirmedOrder sql.NullInt64
	HeaderHash     []byte
	BlockTimestamp sql.NullInt64
	Label          []byte
}

func (q *Queries) GetUnminedTransactionDetails(ctx context.Context, arg GetUnminedTransactionDetailsParams) (GetUnminedTransactionDetailsRow, error) {
	row := q.queryRow(ctx, q.getUnminedTransactionDetailsStmt, GetUnminedTransactionDetails, arg.WalletID, arg.TxHash)
	var i GetUnminedTransactionDetailsRow
	err := row.Scan(
		&i.ID,
		&i.RawTx,
		&i.ReceivedUnix,
		&i.BlockHeight,
		&i.ConfirmedOrder,
		&i.HeaderHash,
		&i.BlockTimestamp,
		&i.Label,
	)
	return i, err
}

const InsertTransaction = `-- name: InsertTransaction :one
INSERT INTO transactions (
    wallet_id, tx_hash, raw_tx, received_unix, block_id,
    confirmed_order, is_coinbase
) VALUES (
    ?1, ?2, ?3,
    ?4,
    (SELECT id FROM blocks WHERE header_hash = ?5),
    cast(?6 AS INTEGER),
    ?7
)
RETURNING id
`

type InsertTransactionParams struct {
	WalletID       int64
	TxHash         []byte
	RawTx          []byte
	ReceivedUnix   int64
	BlockHash      []byte
	ConfirmedOrder sql.NullInt64
	IsCoinbase     bool
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (int64, error) {
	row := q.queryRow(ctx, q.insertTransactionStmt, InsertTransaction,
		arg.WalletID,
		arg.TxHash,
		arg.RawTx,
		arg.ReceivedUnix,
		arg.BlockHash,
		arg.ConfirmedOrder,
		arg.IsCoinbase,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const InsertTransactionInput = `-- name: InsertTransactionInput :exec
INSERT INTO transaction_inputs (
    spending_tx_id, input_index, prev_tx_hash, prev_output_index
) VALUES (?, ?, ?, ?)
`

type InsertTransactionInputParams struct {
	SpendingTxID    int64
	InputIndex      int64
	PrevTxHash      []byte
	PrevOutputIndex int64
}

func (q *Queries) InsertTransactionInput(ctx context.Context, arg InsertTransactionInputParams) error {
	_, err := q.exec(ctx, q.insertTransactionInputStmt, InsertTransactionInput,
		arg.SpendingTxID,
		arg.InputIndex,
		arg.PrevTxHash,
		arg.PrevOutputIndex,
	)
	return err
}

const ListMinedTransactionsForward = `-- name: ListMinedTransactionsForward :many
SELECT t.id, t.wallet_id, t.tx_hash, t.raw_tx, t.received_unix,
       b.block_height, t.confirmed_order, t.is_coinbase,
       b.header_hash, b.block_timestamp
FROM transactions AS t
INNER JOIN blocks AS b ON b.id = t.block_id
WHERE t.wallet_id = ?1
  AND b.block_height BETWEEN cast(?2 AS INTEGER)
                         AND cast(?3 AS INTEGER)
ORDER BY b.block_height ASC, t.confirmed_order ASC
`

type ListMinedTransactionsForwardParams struct {
	WalletID    int64
	StartHeight int64
	EndHeight   int64
}

type ListMinedTransactionsForwardRow struct {
	ID             int64
	WalletID       int64
	TxHash         []byte
	RawTx          []byte
	ReceivedUnix   int64
	BlockHeight    int64
	ConfirmedOrder sql.NullInt64
	IsCoinbase     bool
	HeaderHash     []byte
	BlockTimestamp int64
}

func (q *Queries) ListMinedTransactionsForward(ctx context.Context, arg ListMinedTransactionsForwardParams) ([]ListMinedTransactionsForwardRow, error) {
	rows, err := q.query(ctx, q.listMinedTransactionsForwardStmt, ListMinedTransactionsForward, arg.WalletID, arg.StartHeight, arg.EndHeight)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMinedTransactionsForwardRow
	for rows.Next() {
		var i ListMinedTransactionsForwardRow
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.TxHash,
			&i.RawTx,
			&i.ReceivedUnix,
			&i.BlockHeight,
			&i.ConfirmedOrder,
			&i.IsCoinbase,
			&i.HeaderHash,
			&i.BlockTimestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListMinedTransactionsFromHeight = `-- name: ListMinedTransactionsFromHeight :many
SELECT t.id, t.tx_hash, t.is_coinbase
FROM transactions AS t
INNER JOIN blocks AS b ON b.id = t.block_id
WHERE t.wallet_id = ?1
  AND b.block_height >= cast(?2 AS INTEGER)
ORDER BY b.block_height DESC, t.confirmed_order DESC, t.id DESC
`

type ListMinedTransactionsFromHeightParams struct {
	WalletID int64
	Height   int64
}

type ListMinedTransactionsFromHeightRow struct {
	ID         int64
	TxHash     []byte
	IsCoinbase bool
}

func (q *Queries) ListMinedTransactionsFromHeight(ctx context.Context, arg ListMinedTransactionsFromHeightParams) ([]ListMinedTransactionsFromHeightRow, error) {
	rows, err := q.query(ctx, q.listMinedTransactionsFromHeightStmt, ListMinedTransactionsFromHeight, arg.WalletID, arg.Height)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMinedTransactionsFromHeightRow
	for rows.Next() {
		var i ListMinedTransactionsFromHeightRow
		if err := rows.Scan(&i.ID, &i.TxHash, &i.IsCoinbase); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListMinedTransactionsReverse = `-- name: ListMinedTransactionsReverse :many
SELECT t.id, t.wallet_id, t.tx_hash, t.raw_tx, t.received_unix,
       b.block_height, t.confirmed_order, t.is_coinbase,
       b.header_hash, b.block_timestamp
FROM transactions AS t
INNER JOIN blocks AS b ON b.id = t.block_id
WHERE t.wallet_id = ?1
  AND b.block_height BETWEEN cast(?2 AS INTEGER)
                         AND cast(?3 AS INTEGER)
ORDER BY b.block_height DESC, t.confirmed_order ASC
`

type ListMinedTransactionsReverseParams struct {
	WalletID    int64
	EndHeight   int64
	StartHeight int64
}

type ListMinedTransactionsReverseRow struct {
	ID             int64
	WalletID       int64
	TxHash         []byte
	RawTx          []byte
	ReceivedUnix   int64
	BlockHeight    int64
	ConfirmedOrder sql.NullInt64
	IsCoinbase     bool
	HeaderHash     []byte
	BlockTimestamp int64
}

func (q *Queries) ListMinedTransactionsReverse(ctx context.Context, arg ListMinedTransactionsReverseParams) ([]ListMinedTransactionsReverseRow, error) {
	rows, err := q.query(ctx, q.listMinedTransactionsReverseStmt, ListMinedTransactionsReverse, arg.WalletID, arg.EndHeight, arg.StartHeight)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMinedTransactionsReverseRow
	for rows.Next() {
		var i ListMinedTransactionsReverseRow
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.TxHash,
			&i.RawTx,
			&i.ReceivedUnix,
			&i.BlockHeight,
			&i.ConfirmedOrder,
			&i.IsCoinbase,
			&i.HeaderHash,
			&i.BlockTimestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTransactionIncidencesByHash = `-- name: ListTransactionIncidencesByHash :many
SELECT t.id, t.wallet_id, t.tx_hash, t.raw_tx, t.received_unix,
       t.block_id, t.confirmed_order, t.is_coinbase
FROM transactions AS t
LEFT JOIN blocks AS b ON b.id = t.block_id
WHERE t.wallet_id = ? AND t.tx_hash = ?
ORDER BY t.block_id IS NOT NULL, b.block_height DESC, t.id DESC
`

type ListTransactionIncidencesByHashParams struct {
	WalletID int64
	TxHash   []byte
}

func (q *Queries) ListTransactionIncidencesByHash(ctx context.Context, arg ListTransactionIncidencesByHashParams) ([]Transaction, error) {
	rows, err := q.query(ctx, q.listTransactionIncidencesByHashStmt, ListTransactionIncidencesByHash, arg.WalletID, arg.TxHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.TxHash,
			&i.RawTx,
			&i.ReceivedUnix,
			&i.BlockID,
			&i.ConfirmedOrder,
			&i.IsCoinbase,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUnminedSpenders = `-- name: ListUnminedSpenders :many
SELECT t.id, t.tx_hash, i.input_index
FROM transaction_inputs AS i
INNER JOIN transactions AS t ON t.id = i.spending_tx_id
WHERE t.wallet_id = ?1
  AND t.block_id IS NULL
  AND i.prev_tx_hash = ?2
  AND i.prev_output_index = ?3
  AND t.id <> ?4
ORDER BY t.tx_hash, i.input_index
`

type ListUnminedSpendersParams struct {
	WalletID             int64
	PrevTxHash           []byte
	PrevOutputIndex      int64
	ExcludeTransactionID int64
}

type ListUnminedSpendersRow struct {
	ID         int64
	TxHash     []byte
	InputIndex int64
}

func (q *Queries) ListUnminedSpenders(ctx context.Context, arg ListUnminedSpendersParams) ([]ListUnminedSpendersRow, error) {
	rows, err := q.query(ctx, q.listUnminedSpendersStmt, ListUnminedSpenders,
		arg.WalletID,
		arg.PrevTxHash,
		arg.PrevOutputIndex,
		arg.ExcludeTransactionID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnminedSpendersRow
	for rows.Next() {
		var i ListUnminedSpendersRow
		if err := rows.Scan(&i.ID, &i.TxHash, &i.InputIndex); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUnminedSpendersByPrevHash = `-- name: ListUnminedSpendersByPrevHash :many
SELECT DISTINCT spender.id, spender.tx_hash
FROM transaction_inputs AS input
INNER JOIN transactions AS spender ON spender.id = input.spending_tx_id
WHERE spender.wallet_id = ?1
  AND spender.block_id IS NULL
  AND input.prev_tx_hash = ?2
ORDER BY spender.id
`

type ListUnminedSpendersByPrevHashParams struct {
	WalletID   int64
	PrevTxHash []byte
}

type ListUnminedSpendersByPrevHashRow struct {
	ID     int64
	TxHash []byte
}

func (q *Queries) ListUnminedSpendersByPrevHash(ctx context.Context, arg ListUnminedSpendersByPrevHashParams) ([]ListUnminedSpendersByPrevHashRow, error) {
	rows, err := q.query(ctx, q.listUnminedSpendersByPrevHashStmt, ListUnminedSpendersByPrevHash, arg.WalletID, arg.PrevTxHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnminedSpendersByPrevHashRow
	for rows.Next() {
		var i ListUnminedSpendersByPrevHashRow
		if err := rows.Scan(&i.ID, &i.TxHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUnminedTransactions = `-- name: ListUnminedTransactions :many
SELECT id, wallet_id, tx_hash, raw_tx, received_unix, confirmed_order,
       is_coinbase
FROM transactions
WHERE wallet_id = ? AND block_id IS NULL
ORDER BY tx_hash
`

type ListUnminedTransactionsRow struct {
	ID             int64
	WalletID       int64
	TxHash         []byte
	RawTx          []byte
	ReceivedUnix   int64
	ConfirmedOrder sql.NullInt64
	IsCoinbase     bool
}

func (q *Queries) ListUnminedTransactions(ctx context.Context, walletID int64) ([]ListUnminedTransactionsRow, error) {
	rows, err := q.query(ctx, q.listUnminedTransactionsStmt, ListUnminedTransactions, walletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnminedTransactionsRow
	for rows.Next() {
		var i ListUnminedTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.TxHash,
			&i.RawTx,
			&i.ReceivedUnix,
			&i.ConfirmedOrder,
			&i.IsCoinbase,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const NextBlockTransactionOrder = `-- name: NextBlockTransactionOrder :one
SELECT cast(COALESCE(MAX(confirmed_order) + 1, 0) AS INTEGER)
FROM transactions
WHERE wallet_id = ?
  AND block_id = (SELECT id FROM blocks WHERE header_hash = ?2)
`

type NextBlockTransactionOrderParams struct {
	WalletID  int64
	BlockHash []byte
}

func (q *Queries) NextBlockTransactionOrder(ctx context.Context, arg NextBlockTransactionOrderParams) (int64, error) {
	row := q.queryRow(ctx, q.nextBlockTransactionOrderStmt, NextBlockTransactionOrder, arg.WalletID, arg.BlockHash)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const PromoteUnminedTransaction = `-- name: PromoteUnminedTransaction :one
UPDATE transactions
SET block_id = (SELECT id FROM blocks WHERE header_hash = ?1),
    confirmed_order = ?2
WHERE wallet_id = ?3 AND tx_hash = ?4
  AND block_id IS NULL
RETURNING id
`

type PromoteUnminedTransactionParams struct {
	BlockHash      []byte
	ConfirmedOrder sql.NullInt64
	WalletID       int64
	TxHash         []byte
}

func (q *Queries) PromoteUnminedTransaction(ctx context.Context, arg PromoteUnminedTransactionParams) (int64, error) {
	row := q.queryRow(ctx, q.promoteUnminedTransactionStmt, PromoteUnminedTransaction,
		arg.BlockHash,
		arg.ConfirmedOrder,
		arg.WalletID,
		arg.TxHash,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const PutTransactionLabel = `-- name: PutTransactionLabel :exec
INSERT INTO transaction_labels (wallet_id, tx_hash, label)
VALUES (?, ?, ?)
ON CONFLICT (wallet_id, tx_hash) DO UPDATE SET label = excluded.label
`

type PutTransactionLabelParams struct {
	WalletID int64
	TxHash   []byte
	Label    []byte
}

func (q *Queries) PutTransactionLabel(ctx context.Context, arg PutTransactionLabelParams) error {
	_, err := q.exec(ctx, q.putTransactionLabelStmt, PutTransactionLabel, arg.WalletID, arg.TxHash, arg.Label)
	return err
}
