// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tx_inputs.sql

package sqlc

import (
	"context"
)

const InsertTxInput = `-- name: InsertTxInput :execrows
INSERT INTO tx_inputs (
    wallet_id,
    tx_id,
    input_index,
    prev_tx_hash,
    prev_output_index
) VALUES (
    ?1, ?2, ?3, ?4, ?5
)
ON CONFLICT (tx_id, input_index) DO NOTHING
`

type InsertTxInputParams struct {
	WalletID        int64
	TxID            int64
	InputIndex      int64
	PrevTxHash      []byte
	PrevOutputIndex int64
}

// Records the previous outpoint spent by one input of a wallet-scoped
// transaction.
//
// How:
//   - Writes directly to tx_inputs using the already-resolved spending
//     transaction ID plus the input's previous outpoint.
//   - Stores every input, including inputs that spend outpoints the wallet does
//     not own, so conflict discovery can match shared external inputs.
//   - Uses an explicit conflict target so confirm-reuse replays of the same input
//     are ignored without masking other constraint failures.
//
// Performance:
// - Single-row insert with cheap duplicate suppression via `ON CONFLICT`.
func (q *Queries) InsertTxInput(ctx context.Context, arg InsertTxInputParams) (int64, error) {
	result, err := q.exec(ctx, q.insertTxInputStmt, InsertTxInput,
		arg.WalletID,
		arg.TxID,
		arg.InputIndex,
		arg.PrevTxHash,
		arg.PrevOutputIndex,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const ListActiveUnminedInputSpenders = `-- name: ListActiveUnminedInputSpenders :many
SELECT DISTINCT i.tx_id
FROM tx_inputs AS i
INNER JOIN transactions AS t
    ON i.wallet_id = t.wallet_id AND i.tx_id = t.id
WHERE
    i.wallet_id = ?1
    AND i.prev_tx_hash = ?2
    AND i.prev_output_index = ?3
    AND t.block_height IS NULL
    AND t.tx_status IN (0, 1)
`

type ListActiveUnminedInputSpendersParams struct {
	WalletID        int64
	PrevTxHash      []byte
	PrevOutputIndex int64
}

// Lists the active unmined wallet transactions that spend a given previous
// outpoint.
//
// How:
//   - Matches input rows on the wallet-scoped previous outpoint lookup index.
//   - Joins transactions on the wallet-scoped `(wallet_id, id)` key and keeps
//     only spenders whose transaction is still in the active unmined set
//     (`block_height IS NULL` and `pending`/`published` status). The status
//     predicate stays in the query because the spending transaction's status
//     lives on transactions, not on the input row.
//   - Returns distinct spender transaction IDs so a transaction that spends the
//     same outpoint through more than one input is reported once.
//
// Performance:
//   - Uses the `(wallet_id, prev_tx_hash, prev_output_index)` index to bound the
//     scan to the matching previous outpoint, then the live-only transaction
//     index for the status filter.
func (q *Queries) ListActiveUnminedInputSpenders(ctx context.Context, arg ListActiveUnminedInputSpendersParams) ([]int64, error) {
	rows, err := q.query(ctx, q.listActiveUnminedInputSpendersStmt, ListActiveUnminedInputSpenders, arg.WalletID, arg.PrevTxHash, arg.PrevOutputIndex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var tx_id int64
		if err := rows.Scan(&tx_id); err != nil {
			return nil, err
		}
		items = append(items, tx_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
